- CODE-OF-CONDUCT.md
The CODE-OF-CONDUCT.md file contains information about CoC in the project.
> docs: Add code of conduct information document

- Makefile
- cmd/template/Dockerfile
- cmd/template/fallback.cfg.sample
- cmd/template/main.go
- cmd/template/nri-resource-policy-template-deployment.yaml.in
- cmd/template/policy/template-policy.go
This is an example policy that can be used to develop a new policy with proper functionality.
> Add template policy

- test/e2e/files/nri-resource-policy-template-deployment.yaml.in
Add missing 'yaml.in' for generating template policy deployment yaml.
> test/e2e/files: add missing template deployment.

- test/e2e/files/nri-resource-policy-template-deployment.yaml.in
Add missing .in for generating template policy deployment yaml.
> test/e2e/files: add missing template policy deployment.

- pkg/resmgr/nri.go
When policy is started, it reads the saved container allocations from cache file. This can cause problems if we change the resource allocation policy as the new policy would use the previous resource allocations and not generate allocations based on its own policy. Solve this by forcing re-allocation of resources at startup.
> policy: Cleanup container allocations at startup

- .gitignore
- test/statistics-analysis/README.md
- test/statistics-analysis/manifests/jaeger-deployment.yaml
- test/statistics-analysis/manifests/sleep-deployment.yaml
- test/statistics-analysis/manifests/stress-ng-deployment.yaml
- test/statistics-analysis/prometheus-values.yaml
- test/statistics-analysis/scripts/destroy-deployment.sh
- test/statistics-analysis/scripts/get-jaeger-tracing-data.py
- test/statistics-analysis/scripts/get-prometheus-timeseries-data.py
- test/statistics-analysis/scripts/plot-graphs.py
- test/statistics-analysis/scripts/post-run.sh
- test/statistics-analysis/scripts/pre-run.sh
- test/statistics-analysis/scripts/requirements.txt
- test/statistics-analysis/scripts/run-test.sh
- test/statistics-analysis/scripts/run-tests.sh
The current setup has been used with containerd. Instructions for using and setting up the test can be found in the README.md file.
> test/statistics-analysis: add test setup for viewing container latencies and NRI plugin resource usage

- test/statistics-analysis/README.md
- test/statistics-analysis/scripts/get-jaeger-tracing-data.py
- test/statistics-analysis/scripts/run-test.sh
- test/statistics-analysis/scripts/run-tests.sh
Make things work with crio container runtime.
> test/statistics-analysis: Initial cri-o support

- TODO.md
Remove already done tasks that were marked to be done. Add new tasks for helm chart support and self hosted runner permissions.
> todo: Update the file

- docs/resource-policy/installation.md
Add plugin installation document.
> docs: add plugin installation document

- docs/resource-policy/installation.md
Give an example how to drop a Helm flag to opt in for enabling NRI in containerd automatically.
> docs: improve plugins installation instructions

- deployment/helm/resource-management-policies/balloons/templates/_helpers.tpl
- deployment/helm/resource-management-policies/balloons/templates/daemonset.yaml
- deployment/helm/resource-management-policies/topology-aware/templates/_helpers.tpl
- deployment/helm/resource-management-policies/topology-aware/templates/daemonset.yaml
Improve the usage of labels and selector logic in accordance with Helm best practices for Balloons and TA plugins.
Fixes https://github.com/containers/nri-plugins/pull/118#pullrequestreview-1658410513
> helm: improve labels and selector labels set on the DaemonSet

- .github/ISSUE_TEMPLATE/bug-report.yaml
- .github/ISSUE_TEMPLATE/feature-request.yaml
- .github/ISSUE_TEMPLATE/new-release.md
Add issue templates for bug reports, feature requests and new releases.
> github: issue templates

- deployment/helm/balloons/values.yaml
- deployment/helm/memory-qos/values.yaml
- deployment/helm/memtierd/values.yaml
- deployment/helm/topology-aware/values.yaml
Default to to appVersion from the Chart.yaml.
> helm: don't set initContainerImage:.tag in values.yaml

- scripts/build/helm-publisher.sh
> scripts: update helm-publisher

- deployment/helm/balloons/Chart.yaml
- deployment/helm/memory-qos/Chart.yaml
- deployment/helm/memtierd/Chart.yaml
- deployment/helm/topology-aware/Chart.yaml
- deployment/overlays/balloons/kustomization.yaml
- deployment/overlays/memory-qos/kustomization.yaml
- deployment/overlays/memtierd/kustomization.yaml
- deployment/overlays/topology-aware/kustomization.yaml
Note that the format of image tag name has changed.
> deployment: update deployment files for v0.2.1

- .github/ISSUE_TEMPLATE/new-release.md
- hack/release-helper.sh
For now, it just updates the deployment files image tag and pull policy.
> Add a helper script for preparing the release

- artifacthub-repo.yml
Add artifacthub-repo.yml to get "verified publisher" label in artifacthub.io for our charts.
> [gh-pages] Helm: add artifacthub-repo.yml to get publisher verification.

- cmd/config-manager/main.go
> [release-0.2] config-manager: don't crash if no runtime is found running

- deployment/operator/Makefile
> [release-0.3/#238] makefile: fix operator bundle image tagging

- .github/workflows/e2e-test.yml
- .github/workflows/helm-lint.yaml
- .github/workflows/package-helm.yaml
- .github/workflows/project-checks.yaml
- .github/workflows/publish-helm-charts.yaml
- .github/workflows/publish-images.yaml
- update git checkout action
- update upload-artifact action
- update setup-go action
> github: update github actions

- cmd/plugins/topology-aware/policy/pools.go
Log resource allocation/release/pinning operations at info level. Use pretty-name when logging container pinning.
> topology-aware: log resource operations at info level.

- cmd/plugins/topology-aware/policy/pod-preferences.go
- cmd/plugins/topology-aware/policy/pools.go
- cmd/plugins/topology-aware/policy/resources.go
- docs/resource-policy/policy/topology-aware.md
- pkg/resmgr/cache/cache.go
- pkg/resmgr/cache/container.go
- test/e2e/policies.test-suite/topology-aware/n4c16/test11-reserved-cpu-annotations/code.var.sh
> topology-aware: support preserving CPU and memory pinning

- cmd/plugins/balloons/policy/balloons-policy.go
- docs/resource-policy/policy/balloons.md
- pkg/resmgr/cache/cache.go
- pkg/resmgr/cache/container.go
- test/e2e/policies.test-suite/balloons/n4c16/test05-namespace/code.var.sh
> balloons: support preserving CPU and memory pinning

- docs/resource-policy/policy/balloons.md
- Use word "pre-created" balloons, when referring to balloons created due to minBalloons > 0 at start or at reconfiguration. Fixes #266.
- Always use word "create" when creating new balloons. Never talk about instantiation or balloon instances.
- Use word "containers" instead of "workloads" as the latter may include several containers.
> doc: more consistent terminology in balloons documentation

- cmd/plugins/balloons/policy/balloons-policy.go
This PR is stacked on top of PR #272.
> balloons: fix the order of assigning containers into balloons

- pkg/resmgr/cache/affinity.go
- pkg/resmgr/cache/pod.go
Fixes broken e2e cases in tests 00 and 03.
> cache: fix generated pod scope and simple affinity expressions.

- test/e2e/lib/vm.bash
Launch Qemu always with monitor server listening to a unix socket file in the VM directory. Add test script functions vm-monitor, vm-mem-hw, vm-mem-hotplug, and vm-mem-hotremove.
> e2e: enable running commands in Qemu monitor and hotpluggin memory

- test/e2e/run.sh
Our method of querying github.com/$repo/releases/latest to determine the latest release of containerd, CRI-O or kubernetes is unasafe. The semantics of 'latest' is up to the package maintainer. Since errors happen, we can end up picking and trying to use a too old version. So instead, list releases and version-sort them to find the latest one.
Ideally we would use the official github API to list all tagged releases not marked as a prerelease, and pick the latest one by tag. However, without authenticating that API is severly rate limited and fails often from behind busy proxies. So instead, fetch pages of releases, parse them for release URLs, sort them by version and pick the
> e2e: fetch and version-sort github releases to get latest release.

- Makefile
Let the set of golang unit test be overridden using the TEST_PKGS Makefile variable. It defaults to '.' which will cause all tests to be run.
> build: allow overriding set of unit test to run.

- cmd/plugins/topology-aware/policy/pools.go
Relax hardware topology checks to allow multiple dies sharing a NUMA node, omitting die nodes from the pool tree if necessary on such hardware.
> topology-aware: relax NUMA node topology checks.

- test/e2e/playbook/provision.yaml
Fix broken Ansible playbook (Ubuntu host).
> e2e: fix broken ansible playbook (ubuntu)

- cmd/plugins/template/policy/template-policy.go
> template: golangci-lint fixes.

- cmd/plugins/memtierd/main.go
> memtierd: golangci-lint fixes.

- cmd/plugins/memory-qos/main.go
> memory-qos: golangci-lint fixes.

- pkg/apis/resmgr/v1alpha1/expression.go
> apis/resmgr: golangci-lint fixes.

- pkg/cgroupstats/collector.go
> cgroupstats: golangci-lint fixes.

- pkg/apis/config/v1alpha1/resmgr/control/config.go
> config: golangci-lint fixes.

- pkg/resmgr/control/control.go
- pkg/resmgr/control/cpu/cache.go
- pkg/resmgr/control/cpu/cpu.go
- pkg/resmgr/control/e2e-test/e2e-test.go
> resmgr/control: golangci-lint fixes.

- pkg/healthz/healthz.go
> healthz: golangci-lint fixes.

- pkg/http/http.go
- pkg/http/http_test.go
> http: golangci-lint fixes.

- pkg/log/config.go
- pkg/log/klogcontrol/klogcontrol.go
- pkg/log/log.go
- pkg/log/signal.go
> log: golangci-lint fixes.

- pkg/pidfile/pidfile.go
- pkg/pidfile/pidfile_test.go
> pidfile: golangci-lint fixes.

- cmd/plugins/topology-aware/policy/cache.go
- cmd/plugins/topology-aware/policy/coldstart_test.go
- cmd/plugins/topology-aware/policy/libmem.go
- cmd/plugins/topology-aware/policy/mocks_test.go
- cmd/plugins/topology-aware/policy/node.go
- cmd/plugins/topology-aware/policy/pod-preferences.go
- cmd/plugins/topology-aware/policy/pools.go
- cmd/plugins/topology-aware/policy/pools_test.go
- cmd/plugins/topology-aware/policy/resources.go
- cmd/plugins/topology-aware/policy/topology-aware-policy.go
> topology-aware: golangci-lint fixes.

- pkg/sysfs/parsers.go
- pkg/sysfs/system.go
- pkg/sysfs/utils.go
> sysfs: golangci-lint fixes.

- .github/workflows/package-helm.yaml
This commit ensures Helm packages are signed and their provenance files are uploaded for verification.
> workflow: sign Helm packages and upload provenance files

- pkg/kubernetes/resources.go
Add a forgotten/uncommitted docstring for SetMemoryCapacity.
> kubernetes: add forgotten docstring for SetMemoryCapacity().

- docs/resource-policy/policy/topology-aware.md
- pkg/resmgr/cache/container.go
This PR cleans up and improves annotated topology hint control. In particular, the commits
- add support for enabling pod resource API hints by type
- allow enabling multiple hint types (comma-separated list of 'devices', 'mounts', and 'pod-resources')
- always log hint allow/deny list parsing status
- improve documentation for annotated hint control
> resmgr: improve annotated topology hint control.

- pkg/sysfs/system.go
Make sysfs.CPUFreq.{Min,Max} exported members. Without this a returned CPUFreq is useless. Also, fold baseFreq into the same struct.
> sysfs: export CPUFreq.{Min,Max}.

- pkg/resmgr/nri.go
Update resource data exported to containers also when a container's allocation changes.
> resmgr: update container-exported resource data.

- test/e2e/run.sh
Some versions of vagrant seem to behave pretty badly when downloading images from custom URLs, giving up easily on any networking problems. For instance, `2.2.18` seems to be bad while `2.3.4` seems to be fine. So to avoid version dependent failures, we now download the images first using `wget`, then feed the local file to vagrant as a URL. I hope this gets us rid of the flaky behavior...
> e2e: pre-download and cache custom vagrant images.
