containers/nri-plugins

- TODO.md
- test/e2e/README.md
- test/e2e/files/Vagrantfile.in
- test/e2e/files/crio-nri-enable
- test/e2e/files/crio.service
- test/e2e/lib/vm.bash
- test/e2e/playbook/nri-balloons-plugin-deploy.yaml
- test/e2e/playbook/nri-topology-aware-plugin-deploy.yaml
- test/e2e/playbook/provision.yaml
- test/e2e/run.sh
This will allow user to select either containerd (default) or crio runtime when running the tests.
> e2e: Add cri-o support to tests

- Makefile
Filter for '/nri-plugins/' not '/nri-resource-policy/' for plugin binary dependencies.
> Makefile: fix pkg path thinko for plugin binary deps.

- Makefile
- cmd/balloons/Dockerfile
- cmd/template/Dockerfile
- cmd/topology-aware/Dockerfile
Only build the binary which will end up in the image we are building. Skip other binaries and the build check.
> fixes: build only the right binary for each image.

- cmd/template/Dockerfile
The entrypoint binary name was wrong for the template image, the binary name must contain also the policy name.
> docker: Template image entrypoint was wrong

- pkg/kubernetes/resources.go
This moves period value of MilliCPUToQuota function to be an output instead of an argument as it was before.
Noticed it while rebasing https://github.com/containers/nri-plugins/pull/25.
> pkg/kubernetes: fix expected input & output values of MilliCPUToQuota

- pkg/resmgr/nri.go
Update container state after resource allocation. At that point the container has been created from our point of view. Any subsequent changes to (any resources of) the container must use a ContainerUpdate instead of a ContainerAdjustment. Updating the state correctly will force subsequent changes to be collected as updates.
> fixes: update container state after resource allocation in CreateContainer.

- cmd/topology-aware/policy/pools.go
Do not second guess the already determined CPU type for containers in the kube-system namespace by checking the namespace again. Short circuit assigning reserved-pool containers to the root based on the CPU type alone.
Note that this also allows containers to be opted out from the reserved pool using an explicit
prefer-reserved-cpus.resource-policy.nri.io/pod: "false"
annotation.
> topology-aware: pick reserved pool by CPU type alone.

- .github/workflows/publish-images.yaml
Fix names of published images to not have two occurences of 'nri-plugin' (once in the registry path and once in the package basename).
> .github: fix published image names.

- test/statistics-analysis/scripts/plot-graphs.py
- test/statistics-analysis/scripts/run-tests.sh
Check the existence of deployment files before running any tests. If a deployment file is simply set to "1" or "yes", try picking up the corresponding generated file from its stock location, assuming we're running out of a cloned repository.
> benchmarks: check deployment files prior to tests/use.

- deployment/overlays/balloons/kustomization.yaml
Fix the container name used for the balloons plugin. Currently, we don't patch the container name and as such end up with the container name called nri-resource-policy-topology-aware while it is balloons plugin that is in use. Using kustomize JSON patching, lets us to alter container name.
Example of kustomize generated DaemonSet
**before this patch**
```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
labels:
app: nri-resource-policy
name: nri-resource-policy
namespace: kube-system
spec:
selector:
matchLabels:
app: nri-resource-policy
template:
metadata:
labels:
app: nri-resource-policy
spec:
containers:
- args:
- --host-root
- /host
- --fallback-config
- /etc/nri-resource-policy/nri-resource-policy.cfg
- --pid-file
- /tmp/nri-resource-policy.pid
- -metrics-interval
- 5s
env:
- name: …
```
> kustomize: patch container name to reflect the plugin name

- test/e2e/run_ci.sh
- test/self-hosted-runner/docker/Dockerfile
Prepend each line printed by e2e tests by current time so that it is easier to see how long the various operations take.
> e2e: Add developer friendly output to self hosted runner

- test/e2e/run_ci.sh
Catch the status value of run_ci.sh instead of ts command. This way we will be able to catch if e2e tests failed or not.
> e2e: Fix the return value of run_ci.sh

- pkg/instrumentation/instrumentation.go
- pkg/instrumentation/tracing/tracing.go
- pkg/resmgr/main/main.go
Set up an extra `resource-manager.policy = $policy` attribute in our instrumentation telemetry process/Resource.
> resmgr, instrumentation: tag instrumentation traces with policy name.

- cmd/balloons/main.go
Fix overly zealous unification of policy bootstrap code accidentally converting balloons to topology-aware.
> balloons: pull in balloons policy to balloons NRI plugin binary.

- Makefile
Make plugin binaries depend on the go sources of their own main packages.
> Makefile: better plugin binary dependencies.

- pkg/resmgr/cache/container.go
- pkg/resmgr/resource-manager.go
- pkg/topology/topology.go
Implement coarse control over topology hints by allowing hint generation to be separately disabled for mounts and devices using annotations. In addition to this we still need to implement more fine grained control based on mount and probably also device paths.
> cache: implement coarse topology hint control.

- test/e2e/run_tests.sh
Currently `DEFAULT_DISTRO` can not be tuned via environment variable from terminal because no matter what is set from terminal gets overrided by the same variable in run.sh script which gets executed before we reach variable export here.
Example: `DEFAULT_DISTRO=generic/ubuntu2204 ./run_tests.sh `won't create a ubuntu vm but instead will use fedora.
> e2e: fix test os distro defaulting

- cmd/balloons/nri-resource-policy-balloons-deployment.yaml.in
- test/e2e/files/nri-resource-policy-balloons-deployment.yaml.in
Add missing RBAC permissions to balloons plugin as we have them for TA plugin. Without these permissions pod will fail to work on nodetopologyresources CRD.
Fixes: https://github.com/containers/nri-plugins/issues/52
> deployment: fix missing nodetopologyresources RBAC in balloons plugin

- deployment/base/nri-resource-policy/clusterrole.yaml
- deployment/base/nri-resource-policy/role.yaml
- test/e2e/files/nri-resource-policy-balloons-deployment.yaml.in
NodeReourceTopologies CRD is cluster-scoped resource. As such, RBAC rules related to NodeReourceTopologies should be controlled from ClusterRole object instead of Role object which is more for namespaced objects.
> rbac: control noderesourcetopologies permissions from ClusterRole

- README.md
The NRI plugins documentation can be found at
https://containers.github.io/nri-plugins/devel/docs/index.html
so mention it in readme file.
> readme: Add documentation link to readme file

- docs/resource-policy/policy/container-affinity.md
The affinity annotation name was incorrect, the correct name should start with resource-policy.nri.io
> docs: Fix the annotation name in affinity examples

- pkg/resmgr/nri.go
The response to a Synchronize request is now dumped twice. This PR stops doing it.
> nri: don't dump Synchronize reponse twice.

- cmd/topology-aware/policy/mocks_test.go
- cmd/topology-aware/policy/pod-preferences.go
- cmd/topology-aware/policy/topology-aware-policy.go
- go.mod
- go.sum
- pkg/resmgr/cache/cache.go
- pkg/resmgr/cache/container.go
- pkg/resmgr/cache/utils.go
- pkg/resmgr/nri.go
This patch set implements handling requests to update container resources. This can happen if the cluster has the InPlacePodVerticalScaling feature gate set to true.
The patch series 
- updates our NRI dependencies to the latest HEAD
- updates our stub plugin interfaces with the necessary related changes (context passed from stub to plugin)
- adds functions for storing and retrieving container resource updates in the cache
- hooks the policy into NRI request processing for UpdateContainers
- implements reallocation of resources for the topology-aware policy
> Implement handling of update container requests.

- test/e2e/README.md
- test/self-hosted-runner/README.md
- test/statistics-analysis/README.md
Very minor fixes to various testing related readme files.
> Minor fixes to testing readme files

- docs/resource-policy/installation.md
We have removed the defaulting of the namespace and instead let the users to dictate what namespace they wish to use for installing the Helm chart into.
> docs: installtion instructions updates according to the Helm charts changes 

- deployment/helm/resource-management-policies/balloons/Chart.yaml
- deployment/helm/resource-management-policies/balloons/crds/noderesourcetopology.yaml
- deployment/helm/resource-management-policies/balloons/templates/_helpers.tpl
- deployment/helm/resource-management-policies/balloons/templates/clusterrole.yaml
- deployment/helm/resource-management-policies/balloons/templates/clusterrolebinding.yaml
- deployment/helm/resource-management-policies/balloons/templates/configmap.yaml
- deployment/helm/resource-management-policies/balloons/templates/daemonset.yaml
- deployment/helm/resource-management-policies/balloons/templates/role.yaml
- deployment/helm/resource-management-policies/balloons/templates/rolebinding.yaml
- deployment/helm/resource-management-policies/balloons/templates/serviceaccount.yaml
- deployment/helm/resource-management-policies/balloons/values.yaml
- deployment/helm/resource-management-policies/topology-aware/Chart.yaml
- deployment/helm/resource-management-policies/topology-aware/crds/noderesourcetopology.yaml
- deployment/helm/resource-management-policies/topology-aware/templates/_helpers.tpl
- deployment/helm/resource-management-policies/topology-aware/templates/clusterrole.yaml
- deployment/helm/resource-management-policies/topology-aware/templates/clusterrolebinding.yaml
- deployment/helm/resource-management-policies/topology-aware/templates/configmap.yaml
- deployment/helm/resource-management-policies/topology-aware/templates/daemonset.yaml
- deployment/helm/resource-management-policies/topology-aware/templates/role.yaml
- deployment/helm/resource-management-policies/topology-aware/templates/rolebinding.yaml
- deployment/helm/resource-management-policies/topology-aware/templates/serviceaccount.yaml
- deployment/helm/resource-management-policies/topology-aware/values.yaml
This commit adds a helm chart to install balloons and topology-aware NRI plugins.
To install the chart into local k8s cluster without current default settings, simply running below is enough:
```sh
helm install topology-aware deployment/helm/resource-management-policies/topology-aware/
helm install balloons deployment/helm/resource-management-policies/balloons
```
For testing and just only generating the final YAML without sending it to k8s
```sh
helm install topology-aware deployment/helm/resource-management-policies/topology-aware/ --dry-run > deployment.yaml
helm install balloons deployment/helm/resource-management-policies/balloons --dry-run > deployment.yaml
```
The images currently the Helm chart defaulting to are:
[ghcr.io/containers/nri-plugins/nri-resource-policy-topology-aware:un …
> helm: add helm chart for plugins installations

- .github/workflows/project-checks.yaml
Fix yaml syntax that got broken in
19bbdd5438fd30bf09c7e33930a5877b9f4b4418.
In addition there's another (required) patch to simplify the workflow file.
> github/workflows: fix broken yaml

- docs/conf.py
- docs/requirements.txt
- docs/resource-policy/developers-guide/architecture.md
This relies on the myst parser's (new in v0.19) feature of customizing
external URL schemes with the "myst_url_schemes" configuration option.
We specify new URL schemes "blob" and "tree" which are supposed to be
used for references to blobs (files) and trees (directories) in the git
repo.
This also drops sphinx event hooks ("doctree-resolved" and
"missing-reference"), simplifying the conf.py considerably. They were
useless anyway as they were totally broken and didn't actually fix any
references to repo files.
The downside of this is that the affected references are not shown when
browsing .md files directly from github (as github dosn't handle our
custom 'tree:' and 'blob:' url schemes. However, it should be preferable
to have the cross-references working in the official documentation. …
> docs: fix references to github repo

- go.mod
- go.sum
- pkg/pidfile/pidfile.go
- pkg/pidfile/pidfile_test.go
- pkg/resmgr/cache/container_test.go
- pkg/resmgr/nri.go
- pkg/topology/go.mod
- pkg/topology/go.sum
- pkg/topology/topology.go
Switch from `errors.Wrap` and `errors.Errorf` to `fmt.Errorf`.
> pkg: eliminate usage of obsolete github.com/pkg/errors.

- scripts/build/update-gh-pages.sh
The update-gh-pages.sh builds the version selector at the bottom left corner of the documentation. The baseurl was wrong so all the versioned, stable and devel documentation gave 404 error.
> build: Fix baseurl when building documentation version selector

- .github/workflows/helm-lint.yaml
- deployment/helm/resource-management-policies/balloons/values.scheme.json
- deployment/helm/resource-management-policies/topology-aware/values.scheme.json
- docs/resource-policy/installation.md
This PR adds a GitHub action for linting Helm charts on pull requests and fixes minor issue with namespaces in the Helm chart installation guide.
Helm linter is basically validating helm chart values in a chart's values.yaml file with [JSON schemas](https://json-schema.org/).
> Helm improvments

- deployment/base/nri-resource-policy/daemonset.yaml
- deployment/overlays/balloons/kustomization.yaml
- deployment/overlays/balloons/sample-configmap.yaml
- deployment/overlays/topology-aware/kustomization.yaml
1. Add the "default" suffix of the daemonset.yam to keep with sample-configmap.yaml .
2. Fix the wrong image name, both the topology-aware and balloons policy.
3. Add more sample configurations to the balloon policy.
Signed-off-by: zhi.chang <zhi.chang@intel.com>
> config: Fix configuration files for kustomize

- .github/workflows/helm-lint.yaml
We would like to trigger helm linter github action only when helm directory has been changed on a pull request. Currently, we are doing opposite of that, which means don't run it when helm directory has changed. This commit fixes that bug.
> gihub-action: fix helm linter action trigger path

- cmd/balloons/nri-resource-policy-balloons-deployment.yaml.in
- cmd/template/nri-resource-policy-template-deployment.yaml.in
- cmd/topology-aware/nri-resource-policy-topology-aware-deployment.yaml.in
- deployment/helm/resource-management-policies/balloons/templates/configmap.yaml
- deployment/helm/resource-management-policies/balloons/templates/daemonset.yaml
- deployment/helm/resource-management-policies/topology-aware/templates/configmap.yaml
- deployment/helm/resource-management-policies/topology-aware/templates/daemonset.yaml
This PR corrects the name of the configMap that agents is expecting and also corrects the name of the configMap that used as a base for fallback config.
> Helm chart configmap fixes and some YAML clean up

- .github/workflows/e2e-test.yml
Currently there is no self hosted runner that could run the e2e-test workflow so disable it for now.
> github: Disable e2e-test workflow

- deployment/helm/resource-management-policies/topology-aware/Chart.yaml
Having plugin specific/unique naming is important for the chart and we have currently incorrect naming for the TA plugin. This commit fixes the name of the TA Helm chart.
> helm: fix topology-aware helm chart naming

- deployment/helm/resource-management-policies/balloons/templates/configmap.yaml
- deployment/helm/resource-management-policies/balloons/values.yaml
- deployment/helm/resource-management-policies/topology-aware/templates/configmap.yaml
- deployment/helm/resource-management-policies/topology-aware/values.yaml
- deployment/overlays/balloons/sample-configmap.yaml
- deployment/overlays/topology-aware/sample-configmap.yaml
> helm/kustomize: fix configmaps 

- sample-configs/nri-resource-policy-configmap.example.yaml
RDT configuration is not supported.
> sample-configs: drop rdt from the sample configuration

- cmd/config-manager/Dockerfile
Bump go version to 1.20 to follow the same versioning as in other components of the project.
> config-manager: bump go version to 1.20

- .github/workflows/package-helm.yaml
- .github/workflows/publish-helm-charts.yaml
- deployment/helm/resource-management-policies/balloons/Chart.yaml
- deployment/helm/resource-management-policies/topology-aware/Chart.yaml
- scripts/build/helm-publisher.sh
Add two GitHub actions to automate Helm charts releasing process. First action would be responsible for packaging the charts and pushing them to the releases and the second action is responsible for updating the index.yaml whenever there is a new release available.
In other words, one GitHub action to package helm charts and upload those charts including the source code to GitHub releases and create a draft release. This job gets triggered when a new tag is pushed.
Second GitHub action - to officially release the charts once official release is published. When repo maintainers, publish the draft release this action gets triggered in updates the index.yaml in `gh-pages` branch with the corresponding URLs of the chart packages.
The benefit of storing index.yaml in `gh-pages` is that it will …
> Automate Helm charts releasing process via GitHub action

- .github/workflows/publish-docs.yml
- .github/workflows/publish-helm-charts.yaml
Use github's built-in concurrency, instead.
> github/workflows: ditch softprops/turnstyle action

- .github/workflows/publish-docs.yml
Drop the separate step for fetching gh-pages branch.
Also update the checkout action to the latest version.
> github: use the git checkout action to fetch all refs

- Makefile
- cmd/plugins/memtierd/Dockerfile
- cmd/plugins/memtierd/main.go
- cmd/plugins/memtierd/nri-memtierd-deployment.yaml.in
- deployment/overlays/memtierd/daemonset.yaml
- deployment/overlays/memtierd/kustomization.yaml
- deployment/overlays/memtierd/sample-configmap.yaml
- docs/memory/index.md
- docs/memory/memtierd.md
- sample-configs/nri-memtierd.yaml
- test/e2e/files/nri-memtierd-deployment.yaml.in
- test/e2e/files/nri-memtierd-test-pod.yaml
The nri-memtierd plugin toggles swapping, starts/stops memtierd processes that track and manage memory of containers.
> Add nri-memtierd plugin

- cmd/plugins/memory-qos/Dockerfile
Dockerfile had a dangling reference to nri-memory-qos example configuration file that was moved under sample configs.
> memory-qos: fix image building

- deployment/helm/resource-management-policies/balloons/templates/daemonset.yaml
- deployment/helm/resource-management-policies/topology-aware/templates/daemonset.yaml
If the NRI feature is not enable yet in the runtime, runnig Helm charts with `nri.patchContainerdConfig `parameter set to true will fail because the directory is not created yet. Setting the hostPath volume type to DirectoryOrCreate ensures that we get the directory created in case it's missing.
> deployment: fix the nri volume type to DirectoryOrCreate

- deployment/helm/memory-qos/Chart.yaml
- deployment/helm/memory-qos/templates/_helpers.tpl
- deployment/helm/memory-qos/templates/configmap.yaml
- deployment/helm/memory-qos/templates/daemonset.yaml
- deployment/helm/memory-qos/values.scheme.json
- deployment/helm/memory-qos/values.yaml
- deployment/helm/memtierd/Chart.yaml
- deployment/helm/memtierd/templates/_helpers.tpl
- deployment/helm/memtierd/templates/configmap.yaml
- deployment/helm/memtierd/templates/daemonset.yaml
- deployment/helm/memtierd/values.scheme.json
- deployment/helm/memtierd/values.yaml
- docs/resource-policy/installation.md
This commit adds two new Helm charts for installing memory-qos(https://github.com/containers/nri-plugins/pull/115) and memtierd(https://github.com/containers/nri-plugins/pull/117) NRI plugins via Helm.
> helm: add charts for memtierd and memory-qos

- deployment/helm/resource-management-policies/balloons/values.yaml
- deployment/helm/resource-management-policies/topology-aware/values.yaml
Fix incorrect naming of the config-manager container image in the Helm charts values.yaml.
> helm: fix config-manager image name reference in charts defaults

- cmd/plugins/memtierd/main.go
- cmd/plugins/memtierd/nri-memtierd-deployment.yaml.in
- deployment/overlays/memtierd/daemonset.yaml
- deployment/overlays/memtierd/sample-configmap.yaml
- test/e2e/files/nri-memtierd-deployment.yaml.in
Hardening nri-memtierd deployment.
> nri-memtierd: mount only needed dirs from host

- deployment/helm/memory-qos/Chart.yaml
- deployment/helm/memory-qos/values.yaml
- deployment/helm/memtierd/Chart.yaml
- deployment/helm/memtierd/values.yaml
- deployment/helm/resource-management-policies/balloons/Chart.yaml
- deployment/helm/resource-management-policies/balloons/values.yaml
- deployment/helm/resource-management-policies/topology-aware/Chart.yaml
- deployment/helm/resource-management-policies/topology-aware/values.yaml
This way the default is to fallback to appVersion from the Chart.yaml.
> helm: don't set image.tag in values.yaml

- cmd/config-manager/main.go
- deployment/helm/balloons/templates/daemonset.yaml
- deployment/helm/balloons/values.yaml
- deployment/helm/topology-aware/templates/daemonset.yaml
- deployment/helm/topology-aware/values.yaml
- docs/resource-policy/installation.md
This PR extends config manager code and the plugins helm charts
so that CRI-O users are also able to enable NRI via our charts if they
wish to. Same parameter is used to opt in for the feature in Helm
charts and we don't require users to indicate what container runtime
is being used. Instead the config manager auto-detects the runtime
and does the necessary changes to its configuration file. In scenarios
with multiple active runtimes (e.g., CRI-O and containerd), the
manager gracefully exits and throws an error.
> deployment: refactor config manager to support NRI enabling in CRI-O 

- deployment/helm/memory-qos/templates/daemonset.yaml
- deployment/helm/memory-qos/values.yaml
- deployment/helm/memtierd/templates/daemonset.yaml
- deployment/helm/memtierd/values.yaml
- docs/resource-policy/installation.md
Add init container logic as optional to memtierd and memory-qos plugins Helm charts similarly as in TA and Balloons.
> helm: support NRI enabling prior to running memtierd & memory-qos plugins

- .github/workflows/publish-helm-charts.yaml
Set fetch depth to 0 to fetch all refs (including gh-pages that we need).
> github: fix publish-helm-charts workflow

- .github/workflows/publish-images.yaml
When docker image build  workflow is triggered based on the new tag push which usually includes v as prefix, the workflow drops the v prefix. As such, when `v0.2.0` tag is pushed to GitHub, we end up with `0.2.0` tags in the docker images. This commit fixes the workflow to keep the v prefix. Currently, our deployments are tagging `v0.2.0` tags for the plugins while published images don't include the `v` and deployment are failing.
> workflow: fix the tagging docker images build from new tags

- .github/workflows/publish-images.yaml
When docker image build  workflow is triggered based on the new tag push which usually includes v as prefix, the workflow drops the v prefix. As such, when `v0.2.0` tag is pushed to GitHub, we end up with `0.2.0` tags in the docker images. This commit fixes the workflow to keep the v prefix. Currently, our deployments are tagging `v0.2.0` tags for the plugins while published images don't include the `v` and deployment are failing.
> [release-0.2] images: fix the tagging docker images build from new tags

- .github/workflows/publish-helm-charts.yaml
Backport of https://github.com/containers/nri-plugins/pull/143
> [release-0.2] github: fix publish-helm-charts workflow

- deployment/helm/balloons/templates/daemonset.yaml
- deployment/helm/memory-qos/templates/daemonset.yaml
- deployment/helm/memtierd/templates/daemonset.yaml
- deployment/helm/topology-aware/templates/daemonset.yaml
This PR fixes incorrectly used restartPolicy field. It should be at the Pod level and adjusts restartPolicy from default `Always` to `OnFailure`.
> deployment: adjust Pod restartPolicy to OnFailure

- deployment/helm/balloons/templates/daemonset.yaml
- deployment/helm/memory-qos/templates/daemonset.yaml
- deployment/helm/memtierd/templates/daemonset.yaml
- deployment/helm/topology-aware/templates/daemonset.yaml
This PR fixes incorrectly used restartPolicy field. It should be at the Pod level and adjusts restartPolicy from default `Always` to `OnFailure`.
Backport of https://github.com/containers/nri-plugins/pull/152
> [release-0.2] deployment: adjust Pod restartPolicy to OnFailure

- deployment/helm/balloons/templates/daemonset.yaml
- deployment/helm/memory-qos/templates/daemonset.yaml
- deployment/helm/memtierd/templates/daemonset.yaml
- deployment/helm/topology-aware/templates/daemonset.yaml
The DaemonSet controller currently only supports the `Always` restart policy, which is set by default. This commit addresses the issue of incorrectly set `OnFailure` restart policy in DaemonSet objects of plugins, ensuring that only the `Always` restart policy is used as intended.
Ref: https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/#pod-template
> deployment: drop DaemonSet unsupported OnFailure restartPolicy

- .github/workflows/publish-images.yaml
- scripts/build/get-buildid
- use 'v'-prefixed image version tags
- use 'v'-prefixed versions in binaries
> fixes: fix image tagging scheme in publishing workflow.

- deployment/helm/balloons/templates/daemonset.yaml
- deployment/helm/memory-qos/templates/daemonset.yaml
- deployment/helm/memtierd/templates/daemonset.yaml
- deployment/helm/topology-aware/templates/daemonset.yaml
The DaemonSet controller currently only supports the `Always` restart policy, which is set by default. This commit addresses the issue of incorrectly set `OnFailure` restart policy in DaemonSet objects of plugins, ensuring that only the `Always` restart policy is used as intended.
Ref: https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/#pod-template
Backport of https://github.com/containers/nri-plugins/pull/155
> [release-0.2] drop DaemonSet unsupported OnFailure restartPolicy

- scripts/build/get-buildid
Remove version string mangling for rpm and deb packages. We don't build packages, only binaries and container images now.
> scripts: ditch versions for .rpm and .deb packages.

- deployment/helm/memory-qos/templates/daemonset.yaml
- deployment/helm/memtierd/templates/daemonset.yaml
Use DirectoryOrCreate hostPath type for /var/run/nri in those Helm charts that are not set up like that yet. This should fix failures when NRI in the runtime is enabled by the config-manager init-container, so the /var/run/nri does not exist yet.
> deployment/helm: always use DirectoryOrCreate for /var/run/nri.

- deployment/helm/memory-qos/templates/daemonset.yaml
- deployment/helm/memtierd/templates/daemonset.yaml
Use DirectoryOrCreate hostPath type for /var/run/nri. This should fix failures when NRI in the runtime is enabled by the config-manager init-container, so the /var/run/nri does not exist yet.
Backport of https://github.com/containers/nri-plugins/pull/162
> [release-0.2] always use DirectoryOrCreate for /var/run/nri

- deployment/helm/balloons/templates/daemonset.yaml
- deployment/helm/balloons/values.yaml
- deployment/helm/memory-qos/templates/daemonset.yaml
- deployment/helm/memory-qos/values.yaml
- deployment/helm/memtierd/templates/daemonset.yaml
- deployment/helm/memtierd/values.yaml
- deployment/helm/topology-aware/templates/daemonset.yaml
- deployment/helm/topology-aware/values.yaml
- docs/resource-policy/installation.md
In some clusters, some of the Nodes might have taints which may avoid NRI plugins DaemonSet Pods not to get scheduled on those Nodes. Having an option to pass custom tolerations to plugins DaemonSet object would help to ensure that Pods get scheduled on all the desired Nodes.
> helm: add an option to set tolerations

- scripts/build/get-buildid
Fix up careless commit a5f7ddd0a134 which broke `make site-build`... when run from a git worktree.
> build/docs: make site-build work again from git worktrees.

- Makefile
- cmd/plugins/sgx-epc/Dockerfile
- cmd/plugins/sgx-epc/nri-sgx-epc-deployment.yaml.in
- cmd/plugins/sgx-epc/sgx-epc.go
- deployment/helm/sgx-epc/Chart.yaml
- deployment/helm/sgx-epc/README.md
- deployment/helm/sgx-epc/templates/_helpers.tpl
- deployment/helm/sgx-epc/templates/daemonset.yaml
- deployment/helm/sgx-epc/values.scheme.json
- deployment/helm/sgx-epc/values.yaml
- docs/deployment/index.md
- docs/deployment/sgx-epc.md
- docs/memory/index.md
- docs/memory/sgx-epc.md
- test/e2e/files/nri-sgx-epc-deployment.yaml.in
plugins: add sgx-epc plugin.
Add a plugin for limiting SGX encrypted page cache usage with
pod annotations. Note that the plugin requires a patched cgroup
v2 misc controller with support for something like
echo 'sgx_epc 65536' > /sys/fs/cgroup/$CGRP/misc.max
to work.
> plugins: add sgx-epc plugin.

- deployment/helm/sgx-epc/README.md
Fix a small typo that got spotted but slipped through the initial review.
> deployment/helm/sgx-epc: fix a small README typo.

- deployment/helm/balloons/README.md
- deployment/helm/memory-qos/README.md
- deployment/helm/memtierd/README.md
- deployment/helm/topology-aware/README.md
- fix trailing WS errors that slipped through in Helm Chart READMEs
> deployment: fix trailing whitespace errors.

- deployment/helm/balloons/README.md
- deployment/helm/memory-qos/README.md
- deployment/helm/memtierd/README.md
- deployment/helm/sgx-epc/README.md
- deployment/helm/topology-aware/README.md
- docs/deployment/index.md
- docs/introduction.md
- docs/memory/memory-qos.md
- docs/memory/memtierd.md
- docs/resource-policy/developers-guide/architecture.md
- docs/resource-policy/developers-guide/e2e-test.md
- docs/resource-policy/developers-guide/unit-test.md
- docs/resource-policy/policy/balloons.md
- docs/resource-policy/policy/index.md
- docs/resource-policy/policy/topology-aware.md
- docs/resource-policy/setup.md
Fix the following issues raised by markdownlint:
- https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md#md004---unordered-list-style
- https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md#md005---inconsistent-indentation-for-list-items-at-the-same-level
- https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md#md006---consider-starting-bulleted-lists-at-the-beginning-of-the-line
- https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md#md009---trailing-spaces
- https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md#md010---hard-tabs
- https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md#md012---multiple-consecutive-blank-lines
- https://github.com/markdownlint/markdownlint/blob/main/docs/RULES.md#md013- …
> docs: fix md style

- README.md
Updates README.md to include recently added plugins memtierd, memory-qos and sgx-epc.
> docs: update the main readme with the list of available plugins

- scripts/build/get-buildid
Make the date-based version generated by unknown_version() 'v'-prefixed, too. Make that version valid again (broken by commit a5f7ddd0a134).
> [release-0.2] scripts: don't make unknown version invalid (cherry-picked 97a3e65).

- scripts/build/helm-publisher.sh
Relax the too strict glob.
Signed-off-by: Markus Lehtonen <markus.lehtonen@intel.com>
(cherry picked from commit 20a610f0b94d0abe64782d1ff554f8f89219b6ea)
> [release-0.2] scripts: update helm-publisher

- deployment/helm/balloons/templates/daemonset.yaml
- deployment/helm/balloons/values.yaml
- deployment/helm/memory-qos/templates/daemonset.yaml
- deployment/helm/memory-qos/values.yaml
- deployment/helm/memtierd/templates/daemonset.yaml
- deployment/helm/memtierd/values.yaml
- deployment/helm/topology-aware/templates/daemonset.yaml
- deployment/helm/topology-aware/values.yaml
- docs/resource-policy/installation.md
In some clusters, some of the Nodes might have taints which may avoid NRI plugins DaemonSet Pods not to get scheduled on those Nodes. Having an option to pass custom tolerations to plugins DaemonSet object would help to ensure that Pods get scheduled on all the desired Nodes.
> [release-0.2] helm: add an option to set tolerations (backport of #157)

- .github/workflows/project-checks.yaml
- .github/workflows/publish-images.yaml
Use `release-*` release branch pattern in all workflows (where release branches are referenced).
> .github: use release-* release branch pattern.

- .github/workflows/project-checks.yaml
- .github/workflows/publish-images.yaml
Use `release-*` release branch pattern in all workflows (where release branches are referenced).
> [release-0.2] .github: use release-* release branch pattern.

- cmd/plugins/balloons/policy/balloons-policy.go
Don't delay updating stored configuration when reconfiguring the policy. Some functions in the call-tree (for instance `newBalloon()`), use the stored options, so they could end up using old data otherwise.
This PR is a cherry-pick of #188.
> [release-0.2] balloons: use new config more consistently.

- test/e2e/policies.test-suite/balloons/balloons-configmap.yaml.in
- test/e2e/policies.test-suite/balloons/n4c16/test08-numa/balloons-numa.cfg
- test/e2e/policies.test-suite/balloons/nri-resource-policy.cfg
Fix incorrect config keys in balloons tests. Use more consistent test environment variable names wrt. config keys.
> [release-0.2] test/e2e: fix incorrect Allocat[ion|or]Priority config key.

- cmd/plugins/balloons/policy/balloons-policy.go
- test/e2e/policies.test-suite/balloons/balloons-configmap.yaml.in
- test/e2e/policies.test-suite/balloons/n4c16/test08-numa/balloons-numa.cfg
- test/e2e/policies.test-suite/balloons/nri-resource-policy.cfg
Don't delay updating stored configuration when reconfiguring the policy. Some functions in the call-tree (for instance `newBalloon()`), use the stored options, so they could end up using old data otherwise.
Additionally, fix a few incorrect keys (`AllocationPriority` should be `AllocatorPriority`) in the balloons tests.
@askervin I bumped into this while fixing failing tests for #164 and I realized it is present also in current main/HEAD.   
This patch might not be a fully proper fix (I didn't try to check all the implications). This change might alter behavior on the reconfiguration error code paths, albeit that should be fixed (at least in principle) by the subsequent successful (re)application of the previous configuration, triggered externally by resmgr... Still, I think we probably …
> balloons: use new config more consistently, fix incorrect test config keys.

- test/e2e/policies.test-suite/balloons/n4c16/test02-prometheus-metrics/code.var.sh
Yet the test allowed scheduling pod0 on any package, it erroneously required memory to be pinned on NUMA node 0.
> e2e: fix balloons test02-prometheus-metrics

- test/e2e/playbook/provision.yaml
This PR fixes the following problems in end-to-end test VM provisioning
- configure runc instead of crun as the default runtime for CRI-O
- wait for cilium installation before provisioning is considered done
> test/e2e: test VM provisioning fixes

- test/e2e/files/Makefile.in
- test/e2e/files/Vagrantfile.in
- test/e2e/lib/vm.bash
- test/e2e/playbook/provision.yaml
- test/e2e/run.sh
This PR fixes a number of problems related to vagrant setup and usage in the e2e tests. In particular:
- use Vagrantfile.in as a vagrant ERB template instead of a pre-created Vagrantfile (which latest vagrant init rejects)
- check vagrant status and fail tests if vagrant (init, provision, or up) commands fail
- try using ssh directly, falling back to vagrant ssh only if this fails
- allow default (latest) cilium version to be overridden for tests
These commits have been split out from #164 as a self-contained and largely unrelated set that can be reviewed and merged separately.
> test/e2e: fix vagrant usage, make cilium version configurable.

- cmd/plugins/balloons/policy/balloons-policy.go
- Always print CPU sets in quotes.
- Clearly print CPU sets before and after resizing.
This PR improves debug printing readability, especially in cases of empty cpusets. Aligns debug prints with PR #203.
> balloons: improve debug printing

- cmd/plugins/balloons/policy/cputree_test.go
- CPUTopologyLevel is now a cfgapi type, there is no more custom parser to be tested.
> balloons: fix unit tests

- pkg/topology/topology.go
Extra device support removes limitations on referring to some devices under /sys/devices in cases where referenced devices have notion of local CPUs yet the file has other name than local_cpulist. This supports e2e tests with device locality because added devices have non-trivial set of local CPUs in e2e vms.
> topology: support more devices under /sys/devices

- cmd/plugins/balloons/policy/balloons-policy.go
- cmd/plugins/balloons/policy/cputree.go
- cmd/plugins/balloons/policy/cputree_test.go
- deployment/helm/balloons/crds/config.nri_balloonspolicies.yaml
- docs/resource-policy/policy/balloons.md
- pkg/apis/config/v1alpha1/resmgr/policy/balloons/config.go
- test/e2e/policies.test-suite/balloons/n4c16/test10-allocator-opts/balloons-allocator-opts.cfg
- test/e2e/policies.test-suite/balloons/n4c16/test10-allocator-opts/code.var.sh
Passing E2E tests requires:
- PR #201 (fix topology detection when running policy in container with sysroot set)
- PR #202 (extend topology detection to devices available in e2e virtual machines)
> Add preferCloseToDevices balloon type option

- test/e2e/playbook/provision.yaml
We can't use `ansible.builtin.command` for tasks that create or update files by redirecting output. These all need `ansible.builtin.shell` instead.
> test/e2e: use ansible.builtin.shell for tasks that redirecting output.

- cmd/config-manager/main.go
Don't rely on ListUnitsByPatternsContext method as it might be too new
and missing in some of the distros like Amazon Linux 2. Instead
filter out active units and then loop over those to check if either
containerd or cri-o units exist.
>  config-manager: improve systemd unit listing

- Makefile
Previously, the image building workflow used  an `unknown` tag for all container images and the bundle. However, bundle should strictly follow semantic versioning (semver). This commit introduces the use of the `v0.0.0-unknown` tag instead of `unknown`.
Example failed job: https://github.com/containers/nri-plugins/actions/runs/7289523927/job/19864308055
> image: improve workflow to enforce semver versioning for the bundle

- docs/resource-policy/policy/topology-aware.md
Fix incorrect capitalization of topology-aware CRD parameters in the documentation.
> docs: fix incorrect CRD parameter capitalization in topology-aware documentation.

- deployment/operator/Makefile
- deployment/operator/categories.json
- deployment/operator/config/manifests/bases/nri-plugins-operator.clusterserviceversion.yaml
https://github.com/k8s-operatorhub/community-operators doesn't support adding custom categories and such dropping using custom categories and switching to Openshift Optional to pass CI checks in https://github.com/k8s-operatorhub/community-operators/pull/3685.
> operator: switch to community defined category

- deployment/operator/Makefile
- deployment/operator/config/manager/kustomization.yaml
- deployment/operator/config/manifests/bases/nri-plugins-operator.clusterserviceversion.yaml
- hack/release-helper.sh
Ensure that we `sed` the image tag to the next release tag before pushing a new tag.
This will ensure that when new tag is pushed and image build is started, our images 
will have the right manifests.
> operator: point containerImage tag to the latest release (v0.3.2)

- pkg/resmgr/nri.go
Inject our 'downward API' mount into containers before updating their state to 'created'. Otherwise, if a policy doesn't make any changes to a container during its creation, we incorrectly consider the container as already created and fail to insert the mount.
> resmgr: inject mount before container state update.

- pkg/resmgr/nri.go
Inject our 'downward API' mount into containers before updating their state to 'created'. Otherwise, if a policy doesn't make any changes to a container during its creation, we incorrectly consider the container as already created and fail to insert the mount.
> [release-0.3] resmgr: inject mount before container state update.

- deployment/helm/balloons/README.md
- deployment/helm/balloons/templates/daemonset.yaml
- deployment/helm/balloons/values.schema.json
- deployment/helm/balloons/values.yaml
- deployment/helm/template/README.md
- deployment/helm/template/templates/daemonset.yaml
- deployment/helm/template/values.schema.json
- deployment/helm/template/values.yaml
- deployment/helm/topology-aware/README.md
- deployment/helm/topology-aware/templates/daemonset.yaml
- deployment/helm/topology-aware/values.schema.json
- deployment/helm/topology-aware/values.yaml
- docs/resource-policy/configuration.md
- pkg/agent/agent.go
- sample-configs/balloons-config.yaml
- sample-configs/template-config.yaml
- sample-configs/topologyaware-config.yaml
This patch set
- changes the default configuration group label to `config.nri/group`
- falls back to look for deprecated labels (`group.config.nri`, `resource-policy.nri.io/group`) if the configured label is absent
- allows overriding the default configuration group label on the command line via helm charts
> fixes: rename default config group label, support/fall back to deprecated labels. 

- deployment/helm/balloons/README.md
- deployment/helm/balloons/templates/daemonset.yaml
- deployment/helm/balloons/values.schema.json
- deployment/helm/balloons/values.yaml
- deployment/helm/template/README.md
- deployment/helm/template/templates/daemonset.yaml
- deployment/helm/template/values.schema.json
- deployment/helm/template/values.yaml
- deployment/helm/topology-aware/README.md
- deployment/helm/topology-aware/templates/daemonset.yaml
- deployment/helm/topology-aware/values.schema.json
- deployment/helm/topology-aware/values.yaml
- docs/resource-policy/configuration.md
- pkg/agent/agent.go
- sample-configs/balloons-config.yaml
- sample-configs/template-config.yaml
- sample-configs/topologyaware-config.yaml
Backport of #231 to the 0.3 release branch.
> [release-0.3/#231] fixes: rename default config group label, support/fall back to deprecated labels.

- config/crd/bases/config.nri_balloonspolicies.yaml
- config/crd/bases/config.nri_templatepolicies.yaml
- config/crd/bases/config.nri_topologyawarepolicies.yaml
- deployment/helm/balloons/crds/config.nri_balloonspolicies.yaml
- deployment/helm/template/crds/config.nri_templatepolicies.yaml
- deployment/helm/topology-aware/crds/config.nri_topologyawarepolicies.yaml
- go.mod
- go.sum
- pkg/apis/config/v1alpha1/instrumentation/config.go
- pkg/instrumentation/tracing/tracing.go
This patch fixes a few annoyances in our current OpenTelemetry instrumentation code. In particular, it
- drops support for the discontinued Jaeger-specific exporter
- avoid using resource.Merge() for creating our otel resource
- uses a parent-based probabilistic sampler to span sampling
> instrumentation: fix resource creation, use parent-based sampler.

- pkg/instrumentation/instrumentation.go
- pkg/instrumentation/tracing/exporter.go
- pkg/instrumentation/tracing/sampler.go
- pkg/instrumentation/tracing/tracing.go
Allow tracing to be properly reconfigured via configuration updates, including proper restart of tracing if necessary. 
We can't simply shut down our (global) tracing provider since the global provider can neither be subsequently changed nor restarted. Therefore update the tracing code to
- only flush the provider without shutdown during Stop()
- disable sampling when no endpoint is set
- log any errors encountered during restart
> instrumentation: allow proper reconfiguration of tracing.

- deployment/operator/Makefile
- deployment/operator/README.md
Ensure proper deployment by invoking `copy-crds` and `kustomizations` makefile targets alongside the `deploy` Makefile target. This change guarantees the presence of all necessary CRDs and ensures that kustomization files are appropriately modified before initiating the operator pod.
> operator: ensure to kustomize operator manifests before local deployment

- deployment/operator/Makefile
- deployment/operator/README.md
Backport of #240 
Ensure proper deployment by invoking copy-crds and kustomizations makefile targets alongside the deploy Makefile target. This change guarantees the presence of all necessary CRDs and ensures that kustomization files are appropriately modified before initiating the operator pod.
> [release-0.3/#240] operator: ensure to kustomize operator manifests before local deployment 

- deployment/operator/config/default/kustomization.yaml
Use `patches` instead of `patchesStrategicMerge` with kustomize as `patchesStrategicMerge` is deprecated.
> kustomize: replace patchesStrategicMerge by patches

- deployment/operator/config/default/kustomization.yaml
Use `patches` instead of `patchesStrategicMerge` with kustomize as `patchesStrategicMerge` is deprecated.
Backport of #242
> [release-0.3] kustomize: replace patchesStrategicMerge by patches

- pkg/resmgr/nri.go
Log containers by pretty name during initial sync with the runtime. Log discovered containers simply according to their state as 'created/running' or 'stopped'. Don't refer to them as 'out-of-sync running' or 'stale stopped', since we anyway try to force reallocation of resources.
> resmgr: log containers by pretty name during startup.

- deployment/helm/balloons/templates/daemonset.yaml
- deployment/helm/memory-qos/templates/daemonset.yaml
- deployment/helm/memtierd/templates/daemonset.yaml
- deployment/helm/sgx-epc/templates/daemonset.yaml
- deployment/helm/template/templates/daemonset.yaml
- deployment/helm/topology-aware/templates/daemonset.yaml
Helm is struggling with a regression where integer values get converted to float64 and therefore fail to get later properly injected into templates. For us this hits our integer [nri.]pluginIndex values.
Add a workaround to first force plugin indices to integers before injecting them through templates.
See https://github.com/helm/helm/commit/44a81f63 for more details.
The other alternative considered was this in `values.schema.json`:
```
"pluginIndex": {
"type": "string",
"pattern": "^[0-9][0-9]$"
}
```
Since indices are integers and the above alternative would have also required us to always quote indices in `values.yaml`, this simpler choice of representing integer indices as integer values was chosen.
> helm: add workaround for Helm int/float snafu.

- cmd/plugins/topology-aware/policy/pools.go
- pkg/resmgr/cache/cache.go
- pkg/resmgr/cache/container.go
- pkg/resmgr/nri.go
Note: this PR is stacked on top of #252.
Try doing a better job of detecting and handling redundant UpdateContainer requests which do not really change any of a container's parameters. Such requests are typically sent by an active CPU Manager with the static policy enabled in kubelet.
Before evaluating an update request for redundancy fill in any missing values from the container's current resources. Then if the request looks redundant short-circuit handling it by sending a reply with the current resources. Otherwise pass it on to the policy.
>     resmgr: handle UpdateContainer requests better.

- test/e2e/policies.test-suite/balloons/balloons-config.yaml.in
- test/e2e/policies.test-suite/balloons/helm-config.yaml
Use kHZ instead of MHz in minFreq and maxFreq as required in the real interface. Using wrong units in the tests did not fail because configuring CPU frequencies with any values does not really work in our test VMs. However, using wrong units in tests is misleading for anyone who tries to use similar configuration on bare metal.
> e2e: fix balloons test CPU frequencies

- cmd/plugins/balloons/policy/balloons-policy.go
Log balloon name as a string, not integer.
> balloons: fix logged balloon name.

- Makefile
Lost some hair, if possible, when debugging an image in e2e vm with most recent tags on it, but still containing old code. New code had not compiled, but I failed to notice the error as `make images` happily passed.
> Makefile: stop image building on docker/compiler errors

- cmd/plugins/balloons/policy/balloons-policy.go
- cmd/plugins/balloons/policy/cputree.go
- cmd/plugins/balloons/policy/fillmethod.go
- docs/resource-policy/policy/balloons.md
- test/e2e/policies.test-suite/balloons/n4c16/test01-basic-placement/code.var.sh
- test/e2e/policies.test-suite/balloons/n4c16/test03-reserved/balloons-reserved.cfg
- test/e2e/policies.test-suite/balloons/n4c16/test03-reserved/code.var.sh
This patch makes the built-in balloon types first-class citizens in their configurability and in CPU allocation order.
> Resize the reserved balloon

- .github/workflows/helm-lint.yaml
- .github/workflows/package-helm.yaml
- .github/workflows/publish-helm-charts.yaml
Get rid of warnings in CI logs.
> github: bump azure/setup-helm action to v4

- pkg/agent/agent.go
- pkg/apis/config/v1alpha1/validator.go
Add an interface for custom validation of configuration data. Update agent to use this interface for extra validation if it is implemented by the configuration data in use.
> apis/config,agent: add support for custom config validation.

- .github/workflows/helm-lint.yaml
- .github/workflows/package-helm.yaml
- .github/workflows/publish-helm-charts.yaml
There is v4 tagged ATM, only v4.0.0. Update workflows to use that instead.
See https://github.com/Azure/setup-helm/issues/126
> .github: use azure/setup-helm@v4.0.0.

- pkg/resmgr/cache/cache.go
- pkg/resmgr/cache/container.go
Add "ignore" annotation to enable special containers to opt out from resource allocation of any resource policy. Resource policies can find these containers and their resource requirements from the cache, but they are not requested to allocate, update or release resources of these containers during their lifecycle and on policy Sync().
> cache: support annotations to preserve CPU and memory pinning

- pkg/resmgr/cache/cache.go
- pkg/resmgr/cache/container.go
- pkg/resmgr/cache/pod.go
Enable sorting containers based on the time when they and their pods have been added to the cache.
> cache: store creation time of pod and containers cache objects

- test/e2e/files/Vagrantfile.in
- test/e2e/playbook/provision.yaml
- test/e2e/run.sh
Update e2e test VM provisioning to use the new `pkgs.k8s.io` repositories. Also autodetect and use the latest Kubernetes, containerd and CRI-O versions, unless this is overridden by the user.
> fixes: update k8s repo location, use latest releases in e2e tests.

- cmd/plugins/topology-aware/policy/mocks_test.go
- pkg/apis/resmgr/v1alpha1/evaluable.go
- pkg/apis/resmgr/v1alpha1/expression.go
- pkg/apis/resmgr/v1alpha1/expression_test.go
- pkg/resmgr/cache/cache.go
- pkg/resmgr/cache/container.go
- pkg/resmgr/cache/pod.go
Expose evaluating pod and container key references using the newly added `EvalRef()` Evaluable interface. This lets one evaluate values of key references, something which previously was only done as part of evaluating expressions. Also, introduce `Substitute()` which takes a source string and performs key substitution on it wrt. a subject, using the new `EvalRef()`, to resolve key references in plain ('$key') or well-formed ('${key}') notation.
> cache, resmgr: expose key evaluation, implement key substitution.

- cmd/plugins/balloons/policy/balloons-policy.go
- cmd/plugins/balloons/policy/fillmethod.go
- cmd/plugins/balloons/policy/metrics.go
- cmd/plugins/topology-aware/policy/mocks_test.go
- config/crd/bases/config.nri_balloonspolicies.yaml
- deployment/helm/balloons/crds/config.nri_balloonspolicies.yaml
- docs/resource-policy/policy/balloons.md
- pkg/apis/config/v1alpha1/resmgr/policy/balloons/config.go
- pkg/apis/resmgr/v1alpha1/evaluable.go
- pkg/apis/resmgr/v1alpha1/expression.go
- pkg/apis/resmgr/v1alpha1/expression_test.go
- pkg/resmgr/cache/cache.go
- pkg/resmgr/cache/container.go
- pkg/resmgr/cache/pod.go
- test/e2e/policies.test-suite/balloons/n4c16/test02-prometheus-metrics/code.var.sh
- test/e2e/policies.test-suite/balloons/n4c16/test04-groupby/balloons-groupby.cfg
- test/e2e/policies.test-suite/balloons/n4c16/test04-groupby/code.var.sh
groupBy enables grouping containers into balloon instances.
Stacked on top of PR #277.
> balloons: implement groupBy option

- cmd/plugins/memtierd/Dockerfile
memtierd requires to be built with go 1.22. This patch changes nri-memtierd build not to follow GO_VERSION of all the other plugins. Other options include downgrading memtierd required go version or upgrading GO_VERSION of all nri-plugins.
> memtierd: update the nri-memtierd plugin to use memtierd v0.1.1

- .github/workflows/publish-docs.yml
When building and publishing documentation, install golang toolchain from release tarball if necessary.
> .github: install exact golang version if necessary.

- pkg/sysfs/system.go
Dump system discovery results in a predictable order by looping through packages, nodes and CPU cores by sorted ID order.
> sysfs: dump system discovery results in a more predictable order.

- test/e2e/files/besteffort.yaml.in
- test/e2e/files/burstable.yaml.in
- test/e2e/files/guaranteed.yaml.in
- test/e2e/files/nri-memory-qos-test-pod.yaml
- test/e2e/files/nri-memtierd-test-pod.yaml
- test/e2e/policies.test-suite/balloons/balloons-busybox.yaml.in
- test/e2e/policies.test-suite/topology-aware/n4c16/test03-simple-affinity/guaranteed+affinity.yaml.in
- test/e2e/policies.test-suite/topology-aware/n4c16/test07-mixed-allocations/guaranteed-annotated.yaml.in
- test/e2e/policies.test-suite/topology-aware/n4c16/test11-reserved-cpu-annotations/reserved-annotated.yaml.in
Pull busybox from quay.io/prometheus to avoid dockerhub rate limiting pull errors causing false test failures.
> e2e: pull busybox from quay.io instead of dockerhub.

- scripts/testing/e2e-runner
Add a simple script which can be used to periodically run e2e tests, for instance from a cron job. The script simply clones or fetches a remote/branch, runs a given set of tests, then collects and publishes the results in a directory.
> scripts/testing: add a simple e2e-runner script.

- cmd/plugins/topology-aware/policy/coldstart_test.go
- cmd/plugins/topology-aware/policy/mocks_test.go
- cmd/plugins/topology-aware/policy/pod-preferences.go
- cmd/plugins/topology-aware/policy/pod-preferences_test.go
- cmd/plugins/topology-aware/policy/pools.go
- cmd/plugins/topology-aware/policy/pools_test.go
- cmd/plugins/topology-aware/policy/resources.go
- cmd/plugins/topology-aware/policy/topology-aware-policy.go
- config/crd/bases/config.nri_topologyawarepolicies.yaml
- deployment/helm/balloons/README.md
- deployment/helm/balloons/templates/daemonset.yaml
- deployment/helm/balloons/values.yaml
- deployment/helm/template/README.md
- deployment/helm/template/templates/daemonset.yaml
- deployment/helm/template/values.yaml
- deployment/helm/topology-aware/README.md
- deployment/helm/topology-aware/crds/config.nri_topologyawarepolicies.yaml
- deployment/helm/topology-aware/templates/daemonset.yaml
- deployment/helm/topology-aware/values.yaml
- docs/resource-policy/developers-guide/cpu-allocator.md
- docs/resource-policy/policy/topology-aware.md
- pkg/apis/config/v1alpha1/resmgr/policy/topologyaware/config.go
- pkg/cpuallocator/allocator.go
- test/e2e/policies.test-suite/topology-aware/helm-config.yaml.in
- test/e2e/policies.test-suite/topology-aware/n4c16/test08-cpuprio-allocation/code.var.sh
Add support for configuring the default CPU priority preference and annotating pod-/container-level CPU priority preferences. These determine the preferred priority for CPUs when doing fully or partially exclusive CPU allocation. Priorities are calculated for such allocations and passed on to the CPU allocator which then tries to fulfill these preferences.
With this PR in place, it should be possible on hybrid core architecture systems to configure the policy to prefer allocating energy-efficient cores by default and performance optimized cores to containers annotated with such a preference, or vice versa. Additionally, due to the recently introduced (CPU) cluster-awareness in the CPU allocator, this policy should now do exclusive allocations in a (CPU) cluster-aware fashion, preferring …
> topology-aware: configurable allocation priority

- .github/workflows/package-helm.yaml
- docs/deployment/helm/index.md
This PR publishes unstable Helm Charts by pushing them to the OCI registry, triggered by any push to `main`. The chart version is calculated from the last tag `x.y.z` on `main` then turning it into a chart version `x.y.z+1-unstable`. The image/app version used in the chart is always `unstable`.
[skopeo](https://github.com/containers/skopeo) can be used to list helm charts hosted in an OCI registry. For instance, to list all the available charts for the template policy one can use
`skopeo list-tags docker://ghcr.io/klihub/nri-plugins/helm-charts/nri-resource-policy-template`.
Note that Helm itself is currently unable to search OCI registries, although there is a WiP implementation for Helm OCI registry search here: https://github.com/sabre1041/helm/tree/search-registry. Before this or …
> .github: package and publish unstable Helm charts in image registry.

- .github/workflows/package-helm.yaml
- docs/deployment/helm/index.md
Add latest fixes which I managed to mis-push and thus omit from the merged version. These fix the Helm chart version to have a leading 'v', add a trailing '/helm-charts' to the registry push path and update the documentation accordingly.
> .github: fix unstable chart version and registry path.

- .github/workflows/publish-docs.yml
When triggered from a tag, our gh-pages update script considers this as a new release. This means potentially (if it's the first tag in the vX.Y series) creating a new vX.Y/ subdir in the docs, linking that as the latest stable release etc. We definitely don't want this to happen for devel or rc or such tags. Modifying the workflow file to only act on well-formed release tags (like v1.2.3) is the most straightforward way to fix this.
> github: don't trigger docs update on non-release tags

- .github/workflows/package-helm.yaml
- .github/workflows/publish-docs.yml
- Makefile
- cmd/plugins/balloons/Dockerfile
- cmd/plugins/memory-qos/Dockerfile
- cmd/plugins/memtierd/Dockerfile
- cmd/plugins/sgx-epc/Dockerfile
- cmd/plugins/template/Dockerfile
- cmd/plugins/topology-aware/Dockerfile
- deployment/operator/Makefile
- docs/deployment/helm/index.md
- scripts/build/update-gh-pages.sh
Backport patches needed for publishing unstable Helm charts from the v0.4-release branch.
- #271 
- #299 (not strictly needed but just for cleanly applying subsequent patches)
- #301 
- #302 
- #303 
- #304
> [release-0.4]: enable devel (unstable) Helm charts

- .github/ISSUE_TEMPLATE/new-release.md
Add the creation of a new unnanotated devel-tag for the next release cycle to the release process issue template.
> .github: update issue template for new release.

- .github/workflows/package-helm.yaml
Setting an evironment variable and using that same variable to trigger conditional jobs with 'if:' does not work as expected. Use a dedicated job to decide if we are dealing with a release tag and propagate that decision to the output of the job. Then use the output to trigger either one of a dependent release or unstable job.
> [release-0.5] .github: fix release check for Helm Chart packaging.

- .github/workflows/package-helm.yaml
Setting an evironment variable and using that same variable to trigger conditional jobs with 'if:' does not work as expected. Use a dedicated job to decide if we are dealing with a release tag and propagate that decision to the output of the job. Then use the output to trigger either one of a dependent release or unstable job.
> .github: fix release check for Helm Chart packaging.

- .github/workflows/package-helm.yaml
- .github/workflows/publish-images.yaml
This PR is a backport of #308 to the `release-0.5` branch.
Be more selective with our triggering tags, to allow a simple 'a tag is always a release' logic when deciding whether to build release or development versions of Helm charts. Also, evaluating a condition once then passing the result on in the environment to alternative jobs within the workflow does not work as expected. Therefore, evaluate the condition directly whenever we need the result.
> [release-0.5] fix release check for Helm Chart packaging.

- .github/workflows/publish-images.yaml
If we build images from a shallow clone, `git describe` isn't able to determine a descriptive version derived from the latest tag. Therefore fetch full history with all tags for image builds.
> .github: fetch tags for image build.

- pkg/resmgr/nri.go
We do not have proper connection re-establishment and the policy- agnostic resource management layer will require changes for this to be possible. Until we get that done, exit the plugin when the ttrpc connection goes down instead of just sitting there pretending everything is fine.
> resmgr: exit when ttrpc connection goes down.

- deployment/operator/Makefile
Fix a whitespace error in the operator Makefile to stop editors b*tching about it.
> operator: fix Makefile whitespace error.

- cmd/config-manager/main.go
- config/crd/bases/config.nri_nriplugindeployments.yaml
- deployment/helm/balloons/README.md
- deployment/helm/balloons/templates/daemonset.yaml
- deployment/helm/balloons/values.schema.json
- deployment/helm/balloons/values.yaml
- deployment/helm/memory-qos/README.md
- deployment/helm/memory-qos/templates/daemonset.yaml
- deployment/helm/memory-qos/values.schema.json
- deployment/helm/memory-qos/values.yaml
- deployment/helm/memtierd/README.md
- deployment/helm/memtierd/templates/daemonset.yaml
- deployment/helm/memtierd/values.schema.json
- deployment/helm/memtierd/values.yaml
- deployment/helm/sgx-epc/README.md
- deployment/helm/sgx-epc/templates/daemonset.yaml
- deployment/helm/sgx-epc/values.schema.json
- deployment/helm/sgx-epc/values.yaml
- deployment/helm/template/README.md
- deployment/helm/template/templates/daemonset.yaml
- deployment/helm/template/values.schema.json
- deployment/helm/template/values.yaml
- deployment/helm/topology-aware/README.md
- deployment/helm/topology-aware/templates/daemonset.yaml
- deployment/helm/topology-aware/values.schema.json
- deployment/helm/topology-aware/values.yaml
- deployment/operator/README.md
- deployment/operator/config/samples/config.nri_v1alpha1_nriplugindeployment.yaml
Allow setting NRI plugin registration and request timeouts in the CRI-O or containerd configuration files. Require neither or both timeouts to be given. If both are given, verify that registration timeout is larger than the request timeout.
> config-manager: allow configuring NRI timeouts.

- config/crd/bases/config.nri_nriplugindeployments.yaml
- deployment/operator/README.md
Fix formatting and missing fields in the operator CRD. Otherwise, currently you can't create a CR to tune operator parameters like `patchConfig` or give the `plugin.index`.
> operator: fix formatting and missing fields in the operator crd

- test/e2e/lib/vm.bash
- test/e2e/run.sh
Note: this PR is stacked on top of #323.
Add support for caching and restoring variables per test VM. Once the `latest` github version of CRI-O, containerd or kubernetes has been resolved to a real version tag, save it in the new vm-specific variable cache. Always try restoring these versions from cache before turning to discover them from github. This should significantly reduce how much we punish/bang on github for the full set of our e2e tests.
> e2e: cache and restore latest github versions

- pkg/agent/node-resource-topology.go
- pkg/resmgr/resource-manager.go
You can see the following lines of logging in the balloons plugin for example:
```
I: [         resource-manager         ] updating topology zones...
I: [               agent              ] updating node resource topology CR
```
Currently it is only [TA plugin](https://github.com/containers/nri-plugins/blob/82131f985fbe5d496215c23cd0a198acfed75bcd/cmd/plugins/topology-aware/policy/topology-aware-policy.go#L260) that actually fetches the zone data, while other plugins like balloons doesn't fetch the data even though it has a [method](https://github.com/containers/nri-plugins/blob/82131f985fbe5d496215c23cd0a198acfed75bcd/cmd/plugins/balloons/policy/balloons-policy.go#L291) for that. As such, with this change, we now check if there is a zone data and only if yes, we allow calling methods & …
> resmgr: don't log about NRT CR updates when object isn't created

- cmd/plugins/topology-aware/policy/pod-preferences.go
Don't log effective memory type preference as cold start preference.
> topology-aware: log memory type preference as such.

- cmd/plugins/topology-aware/policy/pools.go
- cmd/plugins/topology-aware/policy/resources.go
- pkg/sysfs/system.go
Treat HBM memory nodes without close CPUs similarly to PMEM nodes, IOW assign them to the closest DRAM node as extra capacity. Also, for now don't ever allocate HBM memory implicitly to containers.
> topology-aware: don't ignore HBM memory nodes without close CPUs.

- pkg/cgroups/cgroupid.go
- pkg/cgroups/cgroupid_linux.go
- pkg/cgroups/cgroupid_other.go
- pkg/topology/topology.go
- pkg/topology/topology_linux.go
- pkg/topology/topology_other.go
This change moves linux-specific functions to `_linux.go` source files and adds stub implementations for other platforms.
> pkg/{cgroups,topology}: move linux-specific functions

- cmd/plugins/topology-aware/policy/pod-preferences.go
- cmd/plugins/topology-aware/policy/pools.go
- docs/resource-policy/policy/topology-aware.md
- pkg/sysfs/system.go
- test/e2e/policies.test-suite/topology-aware/n4c16/test00-basic-placement/code.var.sh
- test/e2e/policies.test-suite/topology-aware/n4c16/test11-reserved-cpu-annotations/code.var.sh
Containers with effective hide-hyperthreads annotation are allowed to run only on the first CPU hyperthread of all physical CPU cores allocated to its pool.
> topology-aware: add support for hide-hyperthreads annotation.

- pkg/cpuallocator/allocator.go
- pkg/sysfs/system.go
This patch series fixes a few problems related to CPU cluster discovery. In particular
- on systems without SMT/hyperthreading use physical clusters as the logical ones, ensuring that we always have logical clusters if we have any
- during CPU cluster discovery, use the correct die ID instead of the incorrect package ID when querying per package CPU clusters
> sysfs,cpuallocator: fix CPU cluster discovery. 

- cmd/plugins/balloons/policy/balloons-policy.go
- cmd/plugins/balloons/policy/cputree.go
- config/crd/bases/config.nri_balloonspolicies.yaml
- deployment/helm/balloons/crds/config.nri_balloonspolicies.yaml
- docs/resource-policy/policy/balloons.md
- pkg/apis/config/v1alpha1/resmgr/policy/balloons/config.go
- pkg/apis/config/v1alpha1/resmgr/policy/balloons/zz_generated.deepcopy.go
- test/e2e/policies.test-suite/balloons/balloons-busybox.yaml.in
- test/e2e/policies.test-suite/balloons/n4c16/test01-basic-placement/code.var.sh
- test/e2e/policies.test-suite/balloons/n4c16/test02-prometheus-metrics/balloons-metrics.cfg
- test/e2e/policies.test-suite/balloons/n4c16/test02-prometheus-metrics/code.var.sh
- Add hideHyperthreads balloon type option.
- Add support for hide-hyperthreads pod annotation that is already available in the topology-aware policy.
> balloons: hideHyperthreads balloon type option and annotation

- pkg/sysfs/system.go
Don't fail for CPU-only NUMA nodes. Treat them as DRAM nodes with 0 bytes of memory attached, but exclude them when calculating average memory size for memory type approximation.
> sysfs: survive NUMA nodes without memory.

- cmd/plugins/topology-aware/policy/mocks_test.go
- pkg/sysfs/system.go
Replace ThreadCount() with {Min,Max}ThreadCount() to better match hybrid core architectures.
> sysfs: allow non-uniform thread count.

- pkg/cpuallocator/allocator.go
Only do CoreKind filtering in clustered allocation when we have multiple CoreKinds available, IOW on hybrid core architectures.
> cpuallocator: don't filter based on single CoreKind.

- cmd/plugins/topology-aware/policy/mocks_test.go
Fix broken mockSysfs by adding missing, recently introduced SingleThreadForCPUs().
> topology-aware: add missing SingleThreadForCPUs() to mockSysfs.

- cmd/plugins/balloons/policy/balloons-policy.go
- config/crd/bases/config.nri_balloonspolicies.yaml
- deployment/helm/balloons/crds/config.nri_balloonspolicies.yaml
- docs/resource-policy/policy/balloons.md
- pkg/apis/config/v1alpha1/resmgr/policy/balloons/config.go
- test/e2e/policies.test-suite/balloons/n4c16/test22-isolcpus/balloons-isolcpus.cfg
- test/e2e/policies.test-suite/balloons/n4c16/test22-isolcpus/code.var.sh
- test/e2e/run.sh
The isolcpus boot parameter allows you to isolate specific CPUs from
the general SMP balancing and scheduler algorithms. Currently, when a
balloon picks up CPUs, it does not differentiate between isolated and
non-isolated CPUs. This change improves the balloon's logic to:
1. Distinguish between isolated and non-isolated CPUs.
2. Allow users to preferably select isolated CPUs, though this is not guaranteed.
3. Avoid using isolated CPUs unless specifically requested by the user via CR.
>  balloons: add support for isolated cpus.

- pkg/cpuallocator/allocator.go
- pkg/sysfs/system.go
This patch series adds support for clustered CPU allocation based on cache groups to the cpuallocator package. In particular with these patches in place, the cpuallocator now
- discovers cache groups on instantiation
- tries to satisfy allocation requests using one or more cache groups
- uses explicit cluster info based allocation only on hybrid core architectures
Allocation always prefers using fully idle cache groups first, fragmenting idle cache groups by partial allocation second, and only resort to using fragmented groups when the allocation cannot be satisfied in any other way. Partial cache group allocations are done in a hyperthread aware fashion, taking full physical cores whenever possible.
The allocator uses the last useful level of cache for clustering. IOW it tries to find …
> cpuallocator: implement clustered allocation based on cache groups.

- test/e2e/lib/host.bash
- test/e2e/lib/vm.bash
- test/e2e/policies.test-suite/balloons/n4c16/test22-isolcpus/code.var.sh
- test/e2e/run.sh
This PR fixes or improves a few functions in the e2e test script library, including 
- fix host-wait-vm-ssh-server being hasty
- reboot and wait for VM by vagrant.
Here's a more detailed description and reasoning for these changes:
ssh -o ConnectTimeout=$timeout's semantics is such that if connection establishment fails early for other reasons, eg. the host IP not being reachable, ssh exits immediately. Rework the waiting function with this in mind. Instead of counting iterations with the incorrect assumption that each iteration would take 1 second, calculate and use a deadline. Also, move the function to lib/host.bash, since that's where we used to keep all host-* script lib functions.
Don't use "vm-command reboot" for rebooting the VM. It is a bit unreliable and gets stuck too often. …
> fixes: fix host-wait-vm-ssh-server, improve vm-reboot.

- test/e2e/policies.test-suite/balloons/n4c16/test22-isolcpus/code.var.sh
- test/e2e/policies.test-suite/topology-aware/n4c16/test00-basic-placement/code.var.sh
This PR fixes failing nightly runs. They fail because the latest introduced case does not clean up the plugin and the first topology-aware test case does start by properly cleaning up potential leftover plugin instances from earlier cases. This PR should fix both.
> fix: clean up plugin at the beginning/end of tests.

- cmd/plugins/balloons/policy/balloons-policy.go
- config/crd/bases/config.nri_balloonspolicies.yaml
- deployment/helm/balloons/crds/config.nri_balloonspolicies.yaml
- docs/resource-policy/policy/balloons.md
- pkg/apis/config/v1alpha1/resmgr/policy/balloons/config.go
Introduce a new parameter `coreType` in Balloons policy for allowing users to express their preference of selecting P-high performance or power efficient cores.
> balloons: add support for power efficient & high performance cores

- test/e2e/playbook/provision.yaml
Fix e2e tests runnning with bridge CNI plugin on fedora. In particular,
- fix non-default CNI plugin binary path on fedora
- configure bridge CNI plugin earlier during provisoning
These fixes should ensure that the node does not stay lingering in NotReady state, causing false test failures/positives.
> e2e: bridge CNI setup fixes for Fedora/containerd. 

- test/e2e/run.sh
*Note: This PR is stacked and depends on #361.*
The latest cilium release is [broken](https://github.com/cilium/cilium-cli/issues/2795). Let's switch to use the bridge plugin by default.
> e2e: use bridge CNI plugin by default.

- .github/workflows/project-checks.yaml
- Makefile
Use a separate workflow step for deps, formatting and code generation. Add missing verification of binary builds.
> CI: verify in smaller steps, verify binary builds.

- cmd/plugins/topology-aware/policy/topology-aware-policy.go
- pkg/resmgr/cache/pod.go
- pkg/resmgr/flags.go
- pkg/resmgr/nri.go
- pkg/resmgr/resource-manager.go
We recently discovered a problem with the generated stream of container lifecycle events with some runtime versions. A side effect of this is that we get Create/Stop events for multiple container instances with seemingly overlapping lifecycle: the latter instance get created before the former one is stopped.
When undetected, such a false overlap might cause overcommit of resources, with both instances temporarily using the full resource set of the offending container. As a workaround, we now track containers also by fully qualified name ($namespace/pod/ctr) and internally generate an event for releasing the resources of the old instance whenever we notice that a creation event would cause a duplicate instance for the same name.
> resmgr: lifecycle overlap detection and workaround.

- go.mod
- go.sum
There is a new release of goresctrl that has some new helper functions required in nri-plugins. As such bumping it to the latest release v0.8.0.
> go mod: bump goresctrl to latest

- test/e2e/lib/vm.bash
- test/e2e/run.sh
Pull and save runtime logs for the duration of the test run after each test.
> e2e: pull and save runtime logs after each test.

- .codespellrc
Ignore the build directory, test directories (at the top level), PNG files and tarballs.
codespell just keeps on giving...
> codespell: ignore more files.

- test/e2e/playbook/provision.yaml
- test/e2e/run.sh
- test/e2e/run_tests.sh
Fedora 37 is EOL. Switch default test distro to fedora 40 and use cloud base image.
> e2e: switch default test distro to fedora/40-cloud-base.

- test/e2e/playbook/provision.yaml
Ubuntu cloud image does not need a DNS fixup.
> e2e: fix provisioning for Ubuntu cloud image.

- test/e2e/lib/vm.bash
- test/e2e/run_tests.sh
Enable vagrant debugging with vagrant_debug=yes set on the command line.
> e2e: enable vagrant debugging.

- test/e2e/run.sh
Take into account that $VM_HOSTNAME's like xyzzy-foobar-22.04 will propagate to the VM distro hostname as xyzzy-foobar-22.
> e2e: adjust $VM_HOSTNAME for policy node config usage.

- test/e2e/run_tests.sh
Skip tests matching \*long\*, \*fuzz\*, or \*stress\* by default. Run them when `skip_long_tests=no` is set.
> e2e: skip long running tests by default.

- pkg/resmgr/control/cpu/api.go
- pkg/resmgr/control/cpu/cpu.go
Avoid enforcing the frequency scaling governor if the user hasn't explicitly requested it. Previously, we attempted to set it regardless, leading to unnecessary error logs. Furthermore, fix formatting issue when logging error case.
> balloons: set frequency scaling governor only when requested

- pkg/resmgr/lib/memory/nodes.go
- pkg/resmgr/lib/memory/nodes_test.go
This patch set fixes
- a docstring/comment typo
- node mask parsing of empty masks
- node mask parsing ID range upper boundary (should be inclusive)
- node mask parsing incorrect slice index for single node IDs
It also adds an obviously necessary minimal test for `ParseNodeMask()`.
> libmem: typo and thinko fixes.

- Tiltfile
This commit adds a Tiltfile to simplify local development with Tilt.
How to use it?
To run balloons policy: `tilt up balloons`
To run topology-aware policy: `tilt up topology-aware`
All it does is:
1. build the binary
2. create a container image and push to a temporary registry
3. deploy the policy Helm chart
> dev: add Tiltfile for local development

- pkg/sysfs/system.go
This PR is an enabler for testing CPU allocations when there are several CPUs that share the same level 2 cache.
> sysfs: enable faking CPU cache configurations using OVERRIDE_SYS_CACHES

- cmd/plugins/balloons/policy/balloons-policy.go
- test/e2e/policies.test-suite/balloons/n4c16/test01-basic-placement/code.var.sh
Containers without CPU requests always pile up to the first balloon where they fit.
This patch enables having multiple balloons in the system so that this kind of containers will be spread equally into them.
This patch is an enabler to fix the issue #385.
> balloons: improve handling of containers with no CPU requests

- pkg/apis/resmgr/v1alpha1/expression.go
- pkg/resmgr/cache/container.go
Resolving "qosclass" failed silently and returned an empty string due to error when "casting" object from interface{} to string. This fails because the resolved value behind the interface{} is of type k8s.io/api/core/v1.PodQOSClass and not (directly) a string. Making sure that the interface{} is directly a string solves the problem.
> resmgr: fix "qosclass" in policy expressions

- test/e2e/files/Vagrantfile.in
- test/e2e/lib/vm.bash
- test/e2e/run.sh
Fix e2e test vagrant setup to
- explicitly require 'dotenv' before dotenv-loading an environment file
- make the vagrant qemu directory configurable using the qemu_dir shell variable
- use a default qemu directory which works on recent Fedora and OpenSUSE distros
> fixes: fix vagrant dotenv loading and default qemu directory.

- .github/workflows/project-checks.yaml
This PR adds a workflow to check and reject PRs that introduce whitespace errors. The method used to check for whitespace errors is a minimalistic `git diff-index --check` against the base ref of the PR.
> .github: add workflow for rejecting PRs that introduce whitespace errors.

- Makefile
- cmd/plugins/balloons/Dockerfile
- cmd/plugins/topology-aware/Dockerfile
Builds debug versions of binaries with "make DEBUG=1" and images with "make DEBUG=1 images". Debug images contain dlv and source files. If a NRI resource policy has been deployed using the debug image, you can attach debugger to it with:
kubectl exec -n kube-system -it nri-resource-policy-POD -- dlv attach 1
For now, the intention is to provide an easy way to build and deploy debuggable images to local e2e test vms. Therefore, debug images are tagged exactly like normal images, and e2e tests use them as is.
> build: enable building debug binaries and images

- test/e2e/lib/command.bash
%04g-target formatting resulted in filenames like -1.0329e+121-vm in some environments. As COMMAND_COUNTER is a natural number, let us format it using %d for consistent results.
> e2e: fix command filenames in test output directories

- deployment/helm/balloons/values.yaml
Introduce a default configuration where Guaranteed containers are all executed on dedicated CPUs while BestEffort and Burstable share CPUs in package (socket) level.
> helm: new balloons default configuration

- pkg/apis/config/v1alpha1/resmgr/policy/balloons/config.go
Use consistently '=' for assignment (instead of ':=') in +kubebuilder:validation tags. Both versions work, but we have earlier used '=' everywhere, so let's stick to that.
> apis/config: use consistent assignment in +kubebuilder:validation tags.

- Makefile
- config/crd/bases/config.nri_balloonspolicies.yaml
- config/crd/bases/config.nri_templatepolicies.yaml
- config/crd/bases/config.nri_topologyawarepolicies.yaml
- deployment/helm/balloons/crds/config.nri_balloonspolicies.yaml
- deployment/helm/template/crds/config.nri_templatepolicies.yaml
- deployment/helm/topology-aware/crds/config.nri_topologyawarepolicies.yaml
Update controller tools to v0.16.5, in particular to get CRD slice/array item pattern-based validation working using the +kubebuilder:validation:items:Pattern tag.
> build: update controller-tools to v0.16.5.

- test/e2e/playbook/provision.yaml
Accept both double and single quotes when looking for cni_bin_dir configuration value to replace.
> e2e: containerd 2.0.0. provisioning fixup.

- cmd/plugins/topology-aware/policy/affinity.go
- cmd/plugins/topology-aware/policy/mocks_test.go
- cmd/plugins/topology-aware/policy/pools_test.go
- cmd/plugins/topology-aware/policy/topology-aware-policy.go
- pkg/resmgr/cache/affinity.go
- pkg/resmgr/cache/cache.go
Fix the handling of implicit affinities corresponding to the `colocate{Pods,Namespaces}` configuration settings. Unregister and reregister disabled and enabled implicit affinities as necessary when we receive a new configuration.
> topology-aware: correctly reconfigure implicit affinities for configuration changes.

- Makefile
When building with DEBUG=1, also use the '-race' golang build flag unless NORACE=1 is also set.
> build: enable race-detector in DEBUG=1 builds.

- Tiltfile
- enable metrics exporting by default
- expose metrics port by default
> Tilt: turn on prometheus metrics exporting by default for local development

- cmd/plugins/balloons/policy/balloons-policy.go
- cmd/plugins/topology-aware/policy/mocks_test.go
- cmd/plugins/topology-aware/policy/resources.go
- cmd/plugins/topology-aware/policy/topology-aware-policy.go
- pkg/cpuallocator/allocator.go
Turn priority of CPUs to allocate/release into an opaque option passed to `cpuallocator.{Allocate,Release}Cpus()`. This should make it much easier to add new options to the allocator in the future.
> cpuallocator, plugins: handle priority as an option.

- cmd/plugins/topology-aware/policy/cache.go
- cmd/plugins/topology-aware/policy/resources.go
When cloning a grant, copy also the assigned memory zone. Failing to do so can result in errors like this during reconfiguration:
```
E: failed to reinstate grants verbatim: topology-aware: failed to get libmem offer for pool "NUMA node #1", grant of default/test/c2: libmem: invalid NodeMask: request without affinity
```
Additionally, also include the container's pretty name in saved grants, just to help post-mortem interpretation.
> fixes: copy assigned memory zone in grant clone.

- config/crd/bases/config.nri_balloonspolicies.yaml
- config/crd/bases/config.nri_templatepolicies.yaml
- config/crd/bases/config.nri_topologyawarepolicies.yaml
- deployment/helm/balloons/crds/config.nri_balloonspolicies.yaml
- deployment/helm/template/crds/config.nri_templatepolicies.yaml
- deployment/helm/topology-aware/crds/config.nri_topologyawarepolicies.yaml
- pkg/apis/config/v1alpha1/instrumentation/config.go
- pkg/metrics/collectors/collectors.go
- pkg/resmgr/main/main.go
Notes: This PR is *stacked on top* of #403.
Add a `metrics/collectors` subpackage to register the fairly standard `buildinfo`, `process` and `golang` runtime collectors. Turn on the `buildinfo` collector by default.
> [stacked 2/5] metrics: add de-facto standard collectors.

- cmd/plugins/balloons/policy/metrics.go
- cmd/plugins/template/policy/template-policy.go
- cmd/plugins/topology-aware/policy/topology-aware-policy.go
- config/crd/bases/config.nri_balloonspolicies.yaml
- config/crd/bases/config.nri_templatepolicies.yaml
- config/crd/bases/config.nri_topologyawarepolicies.yaml
- deployment/helm/balloons/crds/config.nri_balloonspolicies.yaml
- deployment/helm/template/crds/config.nri_templatepolicies.yaml
- deployment/helm/topology-aware/crds/config.nri_topologyawarepolicies.yaml
- pkg/apis/config/v1alpha1/instrumentation/config.go
- pkg/metrics/collectors/collectors.go
- pkg/resmgr/main/main.go
- pkg/resmgr/policy/metrics.go
- pkg/resmgr/policy/policy.go
Notes: This PR is *stacked on top* of #404.
Simplify the policy-backend metrics collection interface, reducing it to a single `GetMetrics()` call and a returned `policy.Metrics` interface, which simply implements the native prometheus collector interface with `Describe()` and `Collect()`. Update policy implementations accordingly.
> [stacked 3/5] metrics: simplify policy/backend metrics collection interface.

- pkg/resmgr/policy/metrics.go
- pkg/resmgr/policy/policy.go
Notes: This PR is *stacked on top* of #408.
Implement collection of policy 'system' prometheus metrics.
For each memory node collect
- memory capcity
- memory usage
- number of containers sharing the node
For each CPU core collect
- total container allocations from that core
- number of containers sharing the core
> [stacked 4/5] metrics: add policy system collector.

- cmd/plugins/topology-aware/policy/metrics.go
- cmd/plugins/topology-aware/policy/topology-aware-policy.go
- docs/resource-policy/policy/topology-aware.md
- pkg/resmgr/lib/memory/zones.go
- pkg/resmgr/policy/metrics.go
- pkg/resmgr/policy/policy.go
Notes: This PR is *stacked on top* of #405.
Implement metrics collection for the topology-aware policy. Currently we collect for each pool/zone
- name, cpuset and memset
- shared pool capacity, allocation, available amount
- memory capacity, allocation, available amount
- number of containers
- number of containers in the shared pool
> [stacked 5/5] metrics: add topology-aware policy metrics collection.

- pkg/agent/agent.go
- pkg/resmgr/resource-manager.go
- test/e2e/policies.test-suite/topology-aware/n4c16/test12-config-status/code.var.sh
- test/e2e/policies.test-suite/topology-aware/n4c16/test12-config-status/custom-config.yaml.in
- test/e2e/run.sh
Update the agent's config notification callback signature and the resmgr notification callaback to propagate errors for the initial configuration back to the source CR before exiting.
> resmgr,agent: propagate startup config error back to CR.

- scripts/testing/e2e-runner
Update test VM directory glob pattern to `test/e2e/n[0-9]*-c*`. This should also catch and clean up the latest VM topology addition (n6-hbm-cxl-fedora-40-cloud-base-containerd) which is now left lingering after nightly test runs.
> scripts: clean up all tests VMs after test.

- pkg/resmgr/cache/cache_test.go
- pkg/resmgr/cache/pod_test.go
Update cache tests for updated `cache.InsertPod()` signature and `pod.PrettyName()` not omitting default namespace any more.
> cache: update tests.

- pkg/resmgr/cache/cache.go
- pkg/resmgr/cache/cache_test.go
- pkg/resmgr/cache/container.go
- pkg/resmgr/cache/container_test.go
- pkg/resmgr/cache/pod.go
- pkg/resmgr/cache/pod_test.go
- pkg/resmgr/cache/utils.go
> cache: golangci-lint fixes.

- pkg/cgroups/cgroupblkio.go
- pkg/cgroups/cgroupstats.go
> cgroups: golangci-lint fixes.

- pkg/cpuallocator/allocator.go
- pkg/cpuallocator/cpuallocator_test.go
> cpuallocator: golangci-lint fixes.

- pkg/instrumentation/instrumentation_test.go
- pkg/instrumentation/metrics/metrics.go
- pkg/instrumentation/tracing/exporter.go
> instrumentation: golangci-lint fixes.

- pkg/resmgr/lib/memory/allocator.go
- pkg/resmgr/lib/memory/allocator_test.go
- pkg/resmgr/lib/memory/request_test.go
- pkg/resmgr/lib/memory/types.go
> libmem: golangci-lint fixes.

- pkg/metrics/metrics.go
- pkg/metrics/metrics_test.go
> metrics: golangci-lint fixes.

- pkg/resmgr/policy/metrics.go
- pkg/resmgr/policy/policy.go
> resmgr/policy: golangci-lint fixes.

- pkg/resmgr/events.go
- pkg/resmgr/main/main.go
- pkg/resmgr/nri.go
- pkg/resmgr/resource-manager.go
> resmgr: golangci-lint fixes.

- cmd/plugins/balloons/policy/balloons-policy.go
- cmd/plugins/balloons/policy/cputree.go
Fix golangci-lint issues... and a few pointless bitching.
> balloons: golangci-lint fixes.

- pkg/agent/pod-resource-api.go
- pkg/agent/podresapi/client.go
- pkg/agent/podresapi/resources.go
- pkg/agent/podresapi/resources_test.go
- pkg/resmgr/cache/cache.go
Merge `PodResourceMap` into `PodResourcesList`. Avoid unnecessary re-listing of pod resources by caching the result of the last `List()` and trying to reuse it to look up resources.
> agent,resmgr: merge PodResources{List,Map}, cache last List() result.

- cmd/plugins/topology-aware/policy/mocks_test.go
This PR fixes a problem that crept in via #423, which was branched off before #450 and was not rebased once that got merged.
> topology-aware: fix mockCache.RefresPods.

- cmd/plugins/balloons/policy/balloons-policy.go
- config/crd/bases/config.nri_balloonspolicies.yaml
- deployment/helm/balloons/crds/config.nri_balloonspolicies.yaml
- docs/resource-policy/policy/balloons.md
- pkg/apis/config/v1alpha1/resmgr/policy/balloons/config.go
- pkg/apis/config/v1alpha1/resmgr/policy/balloons/zz_generated.deepcopy.go
- test/e2e/policies.test-suite/balloons/n6-hbm-cxl/test01-memory-types/balloons-memory-types.cfg
- test/e2e/policies.test-suite/balloons/n6-hbm-cxl/test01-memory-types/code.var.sh
This option enables overriding policy level `pinMemory` option in balloon types.
Use cases:
1. Enable pinning memory of latency critical container to the lowest latency nodes while leaving all other containers completely unpinned.
2. Allow certain containers to access all memory nodes while memory of all other containers would be pinned.
> Add balloon type specific pinMemory option

- config/crd/bases/config.nri_balloonspolicies.yaml
- config/crd/bases/config.nri_templatepolicies.yaml
- config/crd/bases/config.nri_topologyawarepolicies.yaml
- deployment/helm/balloons/crds/config.nri_balloonspolicies.yaml
- deployment/helm/template/crds/config.nri_templatepolicies.yaml
- deployment/helm/topology-aware/crds/config.nri_topologyawarepolicies.yaml
- pkg/apis/config/v1alpha1/resmgr/control/cpu/config.go
- pkg/resmgr/control/cpu/cpu.go
Allow CPU classes to specify only freqGovernor instead of requiring min and max frequencies.
> balloons: do not require minFreq and maxFreq in CPU classes

- cmd/plugins/memtierd/Dockerfile
Align with the rest of the plugins, allowing GO_VERSION to override the golang version used to build the image. This should prevent `nri-memtierd` image build failures after a go patch-level version bump in `go.mod`, when the image has been recently built with the same minor go version, but with a smaller patch level.
> memtierd: allow overriding go version for image build.

- cmd/plugins/memory-qos/Dockerfile
Fixup commit with unsaved editor buffer snafu. Missed in the review of #458.
> golang-fixup: bump go version for memory-qos, too.

- .github/ISSUE_TEMPLATE/new-release.md
- scripts/release/check-artifacts.sh
Update github 'new release' issue template with instructions on how to check released Helm charts.
> scripts,.github: add artifacts checking script, update issue template.

- go.mod
- go.sum
- test/e2e/policies.test-suite/topology-aware/n4c16/test06-fuzz/generate.go
- test/e2e/policies.test-suite/topology-aware/n4c16/test06-fuzz/generate.sh
Purpose of this patch is to drop dependency to fMBT in e2e fuzz test generation. This patch implements parts that were needed from fMBT in go and includes an example for generating tests: a model and a logic what to cover and how to cover it.
> e2e: add pure go stateful fuzz test generator

- .github/workflows/lint.yaml
Enable golangci-lint action write access to checks, to allow the action to annotate code in PRs.
> .github: allow lint action code annotations.

- test/e2e/lib/topology2qemuopts.py
Don't require SEPARATED_OUTPUT_VARS to be set in the environment. Interpret unset one as 0.
> topology2qemuopts: interpret unset SEPARATED_OUTPUT_VARS as 0.

- cmd/plugins/topology-aware/policy/topology-aware-policy.go
This PR updates the reserved cpuset setup code to
- accept a reserved cpuset if it consists of only a single hand-picked isolated CPU
- exclude isolated CPUs from policy-picked reserved cpusets
> topology-aware: exclude isolated CPUs from policy-picked reserved cpusets.

- test/e2e/lib/topology2qemuopts.py
- test/e2e/lib/vm.bash
This patch set fixes
- `topology2qemuopts` to generate correct qemu options for single node VM topologies
- `vm-setup()` to not expect unconditional memory-related options in EXTRA_ARGS
With these fixes in place it is now possible to generate and boot single node multi-socket test VMs.
> e2e: fix qemu option generation and vm-setup for single node test VMs.

- test/e2e/lib/topology2qemuopts.py
This reverts commit 74c95ab6897d218b63f1d371021cc3ea6fda6960.
The reverted commit failed to realize that semantically the 'nodes' topology parameter is 'nodes-per-die'. Therefore it broke qemu topology option generation for configs which had '"nodes": 1'.
> e2e: revert qemu topology option generation breaking commit.

- pkg/resmgr/cache/cache.go
- pkg/resmgr/cache/container.go
Eliminate cache level RDT class 'overlay' and start tracking container RDT class using the NRI provided container member field alone. Update RDT class setter to generate a container adjustment or update.
> resmgr: eliminate extra RDT class 'overlay'.

- pkg/resmgr/cache/cache.go
- pkg/resmgr/cache/container.go
Eliminate cache level block I/O class 'overlay' and start tracking container block I/O class using the NRI provided container member field alone. Update I/O class setter to generate a container adjustment or update.
> resmgr: eliminate extra block I/O class 'overlay'.

- Makefile
Run e2e tests in a dedicated directory to keep test sources separate from any generated artifacts. Allow overriding the default directory (`"e2e-results"`) using the `E2E_WORKDIR` Makefile variable.
> Makefile: run e2e tests in a dedicated directory.

- scripts/testing/e2e-runner
Now that we use a dedicated e2e test workdir, collect unconditionally all test result data from the workdir without using any selective globbing.
> e2e-runner: collect all e2e test result data from the e2e test workdir.

- scripts/testing/e2e-runner
Relax test VM name globbing to discover and include all tests in the generated test summary.
> e2e-runner: generate summary for all tests.

- cmd/plugins/topology-aware/policy/mocks_test.go
- pkg/sysfs/system.go
This is a prerequisite for selecting CPUs so that sharing the same cache between many memory-bandwidth hungry workloads could be avoided.
> system: add a helper for finding CPUs sharing caches

- pkg/udev/doc.go
- pkg/udev/monitor.go
- pkg/udev/reader.go
- scripts/udev-monitor/udev-monitor.go
Implement low-level udev raw reader, event reader and a monitor, with support for property-based event filtering. This should provide enough plumbing to implement memory hotplug/unplug detection.
> pkg/udev: implement udev event reading/monitoring.

- pkg/sysfs/system.go
Fix a bug where all offline cpus were listed under package/die/cluster 0. The Linux kernel hides the topology information of offline cpus so we do not know where they belong.
> sysfs: only discover topology of online cpus

- cmd/plugins/topology-aware/policy/mocks_test.go
- cmd/plugins/topology-aware/policy/node.go
- cmd/plugins/topology-aware/policy/pools.go
- pkg/sysfs/system.go
- pkg/sysfs/system_test.go
This PR reworks and simplifies how the tree of pools is built in the topology-aware policy, using the detected hardware topology.
We now build the tree by walking the topology from sockets to dies to NUMA nodes closest to dies. We assign local CPU and memory close these CPUs in tandem to each pool as we build the tree. Once the tree is built, we go through each pool node again and assign CPUless NUMA nodes to the same nodes where their closest NUMA nodes with CPUs are assigned to.
Like earlier, the tree is constructed to be minimal. If the system has a single socket, we omit the virtual root and use the sole socket as the root pool to represent the whole system (since it would have the same resources as its parent virtual root node). If a socket has a single die, we omit that die from the …
> topology-aware: rework building the topology pool tree.

- test/e2e/lib/vm.bash
- test/e2e/policies.test-suite/balloons/n4c16/test22-isolcpus/code.var.sh
- test/e2e/policies.test-suite/topology-aware/n4c16/test00-basic-placement/code.var.sh
- test/e2e/run.sh
This patch set
- adds a `vm-set-kernel-cmdline` frontend to the already existing `{fedora,ubuntu}-set-kernel-cmdline`
- moves all of these from `run.sh` to `lib/vm.bash`
- fixes isolcpus-resetting snippet in topology-aware test
> e2e: fix isolcpu-resetting snippet in test.

- cmd/plugins/topology-aware/policy/pools.go
- cmd/plugins/topology-aware/policy/resources.go
- pkg/kubernetes/resources.go
- pkg/kubernetes/resources_test.go
- pkg/resmgr/cache/container.go
- pkg/resmgr/cache/utils.go
- pkg/sysfs/utils.go
- test/e2e/files/burstable.yaml.in
- test/e2e/policies.test-suite/topology-aware/n4c16/test14-burstable/code.var.sh
This patch series updates resource management common infra and the topology aware policy to
- pre-calculate a table of OOM Score adjustment to minimum memory request esimates
- use this table to estimate memory request for burstable containers based on their OOM score adjustment
- allocate memory for containers using memory requests (instead of limits)
- prefer pools with enough attached memory to fulfill both a containers memory request and limit
With these patches in place, the K8s scheduler and the NRI reference policies should be better aligned about the amount of available memory on the node.
Notes:
The estimate table is calculated assuming the simpler/simplest request-to-oom-adj formula, IOW assuming 0 pod level extra resource requests.
> topology-aware: allocate burstable container memory by requests.

- cmd/plugins/topology-aware/policy/topology-aware-policy.go
Don't log as fatal (and abort) when we fail to allocate reserved cpuset. Try to propagate the error back to the source config CR as with the rest of the errors.
> topology-aware: more consistent setup error handling.

- .github/workflows/package-helm.yaml
Work around Helm flakiness when packaging/signing multiple charts with a passphrase provided on stdin/pipe by signing one chart at a time.
> .github: sign one Helm chart at a time.

- .github/workflows/publish-olm-bundle.yaml
Even though `bundle/` is specified with a trailing `/`, the directory itself is copied into the target `nri-plugins-operator/.` in https://github.com/k8s-operatorhub/community-operators/pull/5958. Let's be explicit to ensure contents-only copying.
> github: explicitly ensure contents-only copying

- pkg/agent/pod-resource-api.go
- pkg/agent/podresapi/client.go
- pkg/agent/podresapi/resources.go
- pkg/resmgr/nri.go
This patch set fixes a problem which occurs if the Pod Resource API Get() is feature-gated off and one creates subsequently two identical pods with identical containers but with slightly different resources which then have different (NUMA node) locality. Currently, when podresapi.Get() is unavailable we emulate it with a List, followed by a lookup, caching any parsed per pod/container resources and the remaining unparsed slice of the resource list. However, since we miss purging cached items (when a pod is removed), case we fail to refresh the cached list in the aforementioned case.
This patch set adds support for purging cached entries and actively purge pod entries when a pod is stopped or removed.
> resmgr: purge cached pod resource list upon pod stop/removal.

- cmd/plugins/topology-aware/policy/mocks_test.go
- pkg/sysfs/system.go
This helper gathers package, die, node, etc. ids from a set of CPUs. The helper takes care of checking validity/existence of each CPU in the set.
> sysfs: add a helper for gathering whatever IDs related to CPUs

- test/e2e/playbook/provision.yaml
Recent versions of containerd do not build dropped shims. It is realistic to assume that we are building and testing with most recent containerd versions rather than old ones, so let's support that case in our default e2e workflow, too.
This change affects only testing with containerd_src set to a local containerd build.
> e2e: drop old shims from custom-build containerd

- test/e2e/playbook/provision.yaml
Due to containerd configuration change in recent versions, that is switching from bin_dir to bin_dirs, our configuration modification for Fedora stopped working. This patch makes the CNI location fix more robust, and it works with old and new containerd versions.
> e2e: fix CNI directory in recent containerd versions

- cmd/plugins/topology-aware/policy/topology-aware-policy.go
The format of container exported memsets (exposed to containers through the policy injected `/.nri-resource-policy/resources.sh` downward API file) was accidentally altered when we switched to libmem. This patch restores the original format.
> topology-aware: fix format of container-exported memsets.

- .github/workflows/package-helm.yaml
- .github/workflows/publish-images.yaml
This patch set updates the github workflows to allow publishing images and Helm charts for topic-specific test builds. These builds are triggered by pushing to a branch matching test/build/$TOPIC. Images and charts will be named after $TOPIC taken from the test branch name.
For instance, pushing a v0.9 development tree to a branch named `test/build/dra-driver` in the `klihub` fork of the main github repository builds and publishes (among others) this image and chart to the OCI repo `ghcr.io/klihub/nri-plugins`:
- nri-plugins/nri-resource-policy-topology-aware v0.9-dra-driver-unstable
- helm-charts/nri-resource-policy-topology-aware v0.9-dra-driver-unstable
The built chart references the image by default. IOW, once such a build is ready, it can be installed with a single command like this: …
> .github: allow building and publishing per-topic test images and Helm charts.

- docs/Dockerfile
Fix the golang version used in the doc-/site-building image. It can't be a plain 1.24, must be 1.24.X, since it is must resolve to a downloadable release tarball.
> docs: fix golang version.

- go.mod
- go.sum
- pkg/apis/config/v1alpha1/resmgr/control/rdt/config.go
- pkg/log/log.go
- pkg/log/slog-logger.go
- pkg/resmgr/rdt.go
This PR exposes RDT metrics provided by `goresctrl`. These new metrics are available as `rdt` within the `policy` metrics group.
> resmgr: expose RDT metrics.

- go.mod
- go.sum
This PR simply updates go.mod to point to the new v0.9.0 tag of goresctrl. That tag points to the same SHA1 as our current goresctrl reference, so this PR brings no code changes.
> go.{mod,sum}: use new goresctrl tag v0.9.0.

- scripts/build/update-gh-pages.sh
Use --version-sort when sorting versions. Fixes the stable/ symlink that is expected to point to the release with the highest version number.
> scripts/build/update-gh-pages: fix parsing of latest release tag

- cmd/config-manager/Dockerfile
- cmd/mpolset/Dockerfile
- cmd/plugins/balloons/Dockerfile
- cmd/plugins/memory-policy/Dockerfile
- cmd/plugins/memory-qos/Dockerfile
- cmd/plugins/memtierd/Dockerfile
- cmd/plugins/sgx-epc/Dockerfile
- cmd/plugins/template/Dockerfile
- cmd/plugins/topology-aware/Dockerfile
We need to switch our image building to bookworm from bullseye. There are no golang-1.25.x images for bullseye.
> image-build: switch to bookworm for image building.

- test/e2e/files/Vagrantfile.in
- test/e2e/lib/vm.bash
- test/e2e/run.sh
- test/e2e/run_tests.sh
Add support for pulling vagrant images from custom URLs or URLs from default vagrant image locations which are not hosted by Hashicorp. Use fedora 42 cloud base image by default.
> e2e: support custom image URLs, use fedora 42 by default.

- test/e2e/playbook/provision.yaml
Don't fail if partition is already maxed out. Also, if we fail to resize the partition for any other reason, print a warning instead of aborting all test runs.
> e2e: don't fail if partition resize fails.

- test/e2e/lib/vm.bash
Use persistent ansible SSH connections for initial (or forced re)provisioning.
> e2e: use persistent connections for provisioning.

- test/e2e/playbook/provision.yaml
- test/e2e/run.sh
- test/e2e/run_tests.sh
This PR fixes a number recent/remaining problems with vagrant images in e2e tests. In particular,
- adjusts fat-fingered or otherwise wrong cloud image URLs
- allows overriding distro images (for instance to local caches for environments behind proxies)
- fixes post-provisioning ssh connectivity problems with Fedora >= 41 images
- changes default distro consistently to fedora/42.
> e2e: adjust cloud image URLs, allow image override, fix ssh connectivity problems.

- docs/resource-policy/policy/balloons.md
- "cpu: 1" is an error because a string is expected
- add option for handling isolcpus in reset
> docs: fix and improve reset (allow all) affinity

- test/e2e/policies.test-suite/balloons/n4c16/test02-prometheus-metrics/code.var.sh
Two CPUs for a balloon to host pod0c0 and pod0c1 can be allocated from any die, as long as they are located on the same die.
> e2e: fix false failure in balloons test02-prometheus-metrics

- test/e2e/playbook/provision.yaml
Containerd 2.1.x omits the cgroup driver default setting (`SystemdCgroup = false`) from the config file altogether. Our current e2e test provisioning therefore fails to flip the setting to on. Use a bigger hammer to always force it on.
> e2e: always configure systemd cgroup driver for containerd.

- Makefile
- scripts/testing/e2e-runner
- alternate the CRI runtime tests are being run on every other day
- only build the full set of binaries and images once per week, otherwise the minimal set we're going to test
> e2e: alternate test runtimes in tests.
